-- =========================================================
-- TripMate
-- Migration 001: Restaurant Module
-- =========================================================


-- =========================================================
-- 1. REFINE EXISTING RESTAURANTS TABLE
-- =========================================================

alter table public.restaurants
  add column if not exists email text,
  add column if not exists price_range text,
  add column if not exists accepts_reservations boolean not null default true,
  add column if not exists average_preparation_minutes integer,
  add column if not exists updated_at timestamptz not null default now();


-- Validate price range
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'restaurants_price_range_check'
  ) then
    alter table public.restaurants
      add constraint restaurants_price_range_check
      check (
        price_range is null
        or price_range in (
          'budget',
          'moderate',
          'premium',
          'luxury'
        )
      );
  end if;
end $$;


-- Validate preparation time
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'restaurants_preparation_time_check'
  ) then
    alter table public.restaurants
      add constraint restaurants_preparation_time_check
      check (
        average_preparation_minutes is null
        or average_preparation_minutes >= 0
      );
  end if;
end $$;



-- =========================================================
-- 2. RESTAURANT OPENING HOURS
-- =========================================================

create table if not exists public.restaurant_opening_hours (
  id bigint generated by default as identity primary key,

  restaurant_id bigint not null
    references public.restaurants(id)
    on delete cascade,

  day_of_week integer not null
    check (day_of_week between 0 and 6),

  opening_time time,

  closing_time time,

  is_closed boolean not null default false,

  created_at timestamptz not null default now(),

  unique (restaurant_id, day_of_week)
);



-- =========================================================
-- 3. RESTAURANT IMAGES
-- =========================================================

create table if not exists public.restaurant_images (
  id bigint generated by default as identity primary key,

  restaurant_id bigint not null
    references public.restaurants(id)
    on delete cascade,

  image_url text not null,

  image_type text not null default 'gallery'
    check (
      image_type in (
        'cover',
        'gallery',
        'interior',
        'exterior',
        'menu'
      )
    ),

  display_order integer not null default 0,

  created_at timestamptz not null default now()
);



-- =========================================================
-- 4. RESTAURANT FEATURE CATALOG
-- Parking / Wi-Fi / BYOB / Rooftop etc.
-- =========================================================

create table if not exists public.restaurant_feature_catalog (
  id bigint generated by default as identity primary key,

  name text unique not null,

  category text not null
    check (
      category in (
        'facility',
        'seating',
        'accessibility',
        'family',
        'entertainment',
        'payment',
        'policy'
      )
    ),

  is_active boolean not null default true
);



-- =========================================================
-- 5. RESTAURANT <-> FEATURE RELATION
-- Many-to-many
-- =========================================================

create table if not exists public.restaurant_features (
  restaurant_id bigint not null
    references public.restaurants(id)
    on delete cascade,

  feature_id bigint not null
    references public.restaurant_feature_catalog(id)
    on delete cascade,

  details text,

  primary key (restaurant_id, feature_id)
);



-- =========================================================
-- 6. SERVICE MODES
-- =========================================================

create table if not exists public.service_modes (
  id bigint generated by default as identity primary key,

  name text unique not null
);



create table if not exists public.restaurant_service_modes (
  restaurant_id bigint not null
    references public.restaurants(id)
    on delete cascade,

  service_mode_id bigint not null
    references public.service_modes(id)
    on delete cascade,

  primary key (restaurant_id, service_mode_id)
);



-- =========================================================
-- 7. CUISINES
-- =========================================================

create table if not exists public.cuisines (
  id bigint generated by default as identity primary key,

  name text unique not null
);



create table if not exists public.restaurant_cuisines (
  restaurant_id bigint not null
    references public.restaurants(id)
    on delete cascade,

  cuisine_id bigint not null
    references public.cuisines(id)
    on delete cascade,

  primary key (restaurant_id, cuisine_id)
);



-- =========================================================
-- 8. DIETARY OPTIONS
-- =========================================================

create table if not exists public.dietary_options (
  id bigint generated by default as identity primary key,

  name text unique not null
);



create table if not exists public.restaurant_dietary_options (
  restaurant_id bigint not null
    references public.restaurants(id)
    on delete cascade,

  dietary_option_id bigint not null
    references public.dietary_options(id)
    on delete cascade,

  primary key (restaurant_id, dietary_option_id)
);



-- =========================================================
-- 9. FOOD CATEGORIES
-- =========================================================

create table if not exists public.food_categories (
  id bigint generated by default as identity primary key,

  restaurant_id bigint not null
    references public.restaurants(id)
    on delete cascade,

  name text not null,

  display_order integer not null default 0,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),

  unique (restaurant_id, name)
);



-- =========================================================
-- 10. REFINE EXISTING FOOD ITEMS
-- =========================================================

alter table public.food_items
  add column if not exists category_id bigint,
  add column if not exists currency text not null default 'LKR',
  add column if not exists preparation_minutes integer,
  add column if not exists updated_at timestamptz not null default now();


-- Convert any existing text categories into category records
insert into public.food_categories (
  restaurant_id,
  name
)
select distinct
  restaurant_id,
  trim(category)
from public.food_items
where category is not null
  and trim(category) <> ''
on conflict (restaurant_id, name)
do nothing;


-- Link existing food items to their new category
update public.food_items fi
set category_id = fc.id
from public.food_categories fc
where fi.category_id is null
  and fi.category is not null
  and fi.restaurant_id = fc.restaurant_id
  and trim(fi.category) = fc.name;


-- Add foreign key only if it does not already exist
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'food_items_category_id_fkey'
  ) then
    alter table public.food_items
      add constraint food_items_category_id_fkey
      foreign key (category_id)
      references public.food_categories(id)
      on delete set null;
  end if;
end $$;


-- Validate preparation time
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'food_items_preparation_minutes_check'
  ) then
    alter table public.food_items
      add constraint food_items_preparation_minutes_check
      check (
        preparation_minutes is null
        or preparation_minutes >= 0
      );
  end if;
end $$;



-- =========================================================
-- 11. FOOD ITEM DIETARY TAGS
-- Example: one food can be Vegetarian + Gluten-Free
-- =========================================================

create table if not exists public.food_item_dietary_options (
  food_item_id bigint not null
    references public.food_items(id)
    on delete cascade,

  dietary_option_id bigint not null
    references public.dietary_options(id)
    on delete cascade,

  primary key (food_item_id, dietary_option_id)
);



-- =========================================================
-- 12. REFINE BUFFET PACKAGES
-- =========================================================

alter table public.buffet_packages
  add column if not exists currency text not null default 'LKR',
  add column if not exists minimum_guests integer,
  add column if not exists maximum_guests integer,
  add column if not exists updated_at timestamptz not null default now();


do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'buffet_minimum_guests_check'
  ) then
    alter table public.buffet_packages
      add constraint buffet_minimum_guests_check
      check (
        minimum_guests is null
        or minimum_guests > 0
      );
  end if;
end $$;


do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'buffet_maximum_guests_check'
  ) then
    alter table public.buffet_packages
      add constraint buffet_maximum_guests_check
      check (
        maximum_guests is null
        or maximum_guests > 0
      );
  end if;
end $$;


do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'buffet_guest_range_check'
  ) then
    alter table public.buffet_packages
      add constraint buffet_guest_range_check
      check (
        maximum_guests is null
        or minimum_guests is null
        or maximum_guests >= minimum_guests
      );
  end if;
end $$;



-- =========================================================
-- 13. BUFFET ITEMS
-- =========================================================

create table if not exists public.buffet_items (
  id bigint generated by default as identity primary key,

  buffet_id bigint not null
    references public.buffet_packages(id)
    on delete cascade,

  item_name text not null,

  category text,

  description text,

  display_order integer not null default 0
);



-- =========================================================
-- 14. RESTAURANT OFFERS
-- =========================================================

create table if not exists public.restaurant_offers (
  id bigint generated by default as identity primary key,

  restaurant_id bigint not null
    references public.restaurants(id)
    on delete cascade,

  title text not null,

  description text,

  offer_type text not null
    check (
      offer_type in (
        'percentage',
        'fixed_amount',
        'special_price',
        'package'
      )
    ),

  discount_value numeric(12,2),

  minimum_spend numeric(12,2),

  start_date date,

  end_date date,

  terms_and_conditions text,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),

  check (
    discount_value is null
    or discount_value >= 0
  ),

  check (
    minimum_spend is null
    or minimum_spend >= 0
  ),

  check (
    end_date is null
    or start_date is null
    or end_date >= start_date
  )
);



-- =========================================================
-- 15. RESTAURANT AVAILABILITY / TEMPORARY CLOSURES
-- =========================================================

create table if not exists public.restaurant_availability (
  id bigint generated by default as identity primary key,

  restaurant_id bigint not null
    references public.restaurants(id)
    on delete cascade,

  date date not null,

  is_available boolean not null default true,

  opening_time_override time,

  closing_time_override time,

  reason text,

  unique (restaurant_id, date)
);



-- =========================================================
-- 16. RESTAURANT POLICIES
-- BYOB details, dress code, reservation rules etc.
-- =========================================================

create table if not exists public.restaurant_policies (
  id bigint generated by default as identity primary key,

  restaurant_id bigint unique not null
    references public.restaurants(id)
    on delete cascade,

  reservation_policy text,

  cancellation_policy text,

  byob_policy text,

  corkage_fee numeric(12,2),

  dress_code text,

  smoking_policy text,

  children_policy text,

  additional_rules text,

  updated_at timestamptz not null default now(),

  check (
    corkage_fee is null
    or corkage_fee >= 0
  )
);



-- =========================================================
-- 17. INDEXES
-- Speeds up commonly used lookups
-- =========================================================

create index if not exists idx_restaurants_owner_id
on public.restaurants(owner_id);

create index if not exists idx_restaurants_location
on public.restaurants(latitude, longitude);

create index if not exists idx_food_items_restaurant_id
on public.food_items(restaurant_id);

create index if not exists idx_food_items_category_id
on public.food_items(category_id);

create index if not exists idx_buffet_packages_restaurant_id
on public.buffet_packages(restaurant_id);

create index if not exists idx_restaurant_offers_restaurant_id
on public.restaurant_offers(restaurant_id);

create index if not exists idx_restaurant_availability_restaurant_date
on public.restaurant_availability(restaurant_id, date);



-- =========================================================
-- 18. AUTO UPDATE updated_at
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


drop trigger if exists set_restaurants_updated_at
on public.restaurants;

create trigger set_restaurants_updated_at
before update on public.restaurants
for each row
execute procedure public.set_updated_at();


drop trigger if exists set_food_items_updated_at
on public.food_items;

create trigger set_food_items_updated_at
before update on public.food_items
for each row
execute procedure public.set_updated_at();


drop trigger if exists set_buffet_packages_updated_at
on public.buffet_packages;

create trigger set_buffet_packages_updated_at
before update on public.buffet_packages
for each row
execute procedure public.set_updated_at();


drop trigger if exists set_restaurant_policies_updated_at
on public.restaurant_policies;

create trigger set_restaurant_policies_updated_at
before update on public.restaurant_policies
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 19. DEFAULT REFERENCE DATA
-- =========================================================

insert into public.service_modes (name)
values
  ('Dine-in'),
  ('Takeaway'),
  ('Delivery'),
  ('Pickup')
on conflict (name)
do nothing;


insert into public.cuisines (name)
values
  ('Sri Lankan'),
  ('Indian'),
  ('Chinese'),
  ('Italian'),
  ('Japanese'),
  ('Thai'),
  ('Seafood'),
  ('International'),
  ('Fast Food'),
  ('Cafe')
on conflict (name)
do nothing;


insert into public.dietary_options (name)
values
  ('Vegetarian'),
  ('Vegan'),
  ('Halal Options'),
  ('Gluten-Free'),
  ('Dairy-Free')
on conflict (name)
do nothing;


insert into public.restaurant_feature_catalog (
  name,
  category
)
values
  ('Parking', 'facility'),
  ('Wi-Fi', 'facility'),
  ('Air Conditioning', 'facility'),

  ('Outdoor Seating', 'seating'),
  ('Rooftop Seating', 'seating'),

  ('Wheelchair Access', 'accessibility'),

  ('Kids Menu', 'family'),
  ('Family Friendly', 'family'),

  ('Live Music', 'entertainment'),

  ('Card Payments', 'payment'),
  ('Digital Payments', 'payment'),

  ('BYOB', 'policy'),
  ('Smoking Area', 'policy'),
  ('Non-Smoking Area', 'policy')
on conflict (name)
do nothing;
