-- =========================================================
-- TripMate
-- Migration 002: Restaurant Security / RLS
-- Part A
-- =========================================================


-- =========================================================
-- 1. PROVIDER VERIFICATION
-- =========================================================

create table if not exists public.provider_verifications (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references public.profiles(id)
    on delete cascade,

  provider_type text not null
    check (
      provider_type in (
        'restaurant',
        'accommodation',
        'driver'
      )
    ),

  status text not null default 'pending'
    check (
      status in (
        'pending',
        'approved',
        'rejected',
        'suspended'
      )
    ),

  submitted_at timestamptz not null default now(),

  reviewed_by uuid
    references public.profiles(id)
    on delete set null,

  reviewed_at timestamptz,

  admin_notes text,

  unique (user_id, provider_type)
);


alter table public.provider_verifications
enable row level security;



-- =========================================================
-- 2. PROVIDER CAN VIEW OWN VERIFICATION
-- =========================================================

drop policy if exists
"Users can view own provider verification"
on public.provider_verifications;

create policy
"Users can view own provider verification"
on public.provider_verifications

for select
to authenticated

using (
  user_id = auth.uid()
);



-- =========================================================
-- 3. PROVIDER CAN SUBMIT OWN VERIFICATION REQUEST
-- =========================================================

drop policy if exists
"Users can submit own provider verification"
on public.provider_verifications;

create policy
"Users can submit own provider verification"
on public.provider_verifications

for insert
to authenticated

with check (

  user_id = auth.uid()

  and status = 'pending'

  and (

    (
      provider_type = 'restaurant'

      and exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.role = 'restaurant_owner'
      )
    )

    or

    (
      provider_type = 'accommodation'

      and exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.role = 'accommodation_owner'
      )
    )

    or

    (
      provider_type = 'driver'

      and exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.role = 'driver'
      )
    )

  )
);



-- =========================================================
-- 4. HELPER: CHECK PROVIDER APPROVAL
-- =========================================================

create or replace function public.is_provider_approved(
  target_user_id uuid,
  target_provider_type text
)

returns boolean

language sql
stable
security definer

set search_path = ''

as $$

  select exists (

    select 1

    from public.provider_verifications pv

    where pv.user_id = target_user_id

      and pv.provider_type = target_provider_type

      and pv.status = 'approved'

  );

$$;


revoke all
on function public.is_provider_approved(uuid, text)
from public;

grant execute
on function public.is_provider_approved(uuid, text)
to anon, authenticated;



-- =========================================================
-- 5. HELPER: CHECK RESTAURANT OWNERSHIP
-- =========================================================

create or replace function public.is_restaurant_owner(
  target_restaurant_id bigint
)

returns boolean

language sql
stable
security definer

set search_path = ''

as $$

  select exists (

    select 1

    from public.restaurants r

    join public.profiles p
      on p.id = r.owner_id

    where r.id = target_restaurant_id

      and r.owner_id = auth.uid()

      and p.role = 'restaurant_owner'

  );

$$;


revoke all
on function public.is_restaurant_owner(bigint)
from public;

grant execute
on function public.is_restaurant_owner(bigint)
to authenticated;



-- =========================================================
-- 6. HELPER: CHECK IF RESTAURANT CAN BE PUBLICLY VIEWED
-- =========================================================

create or replace function public.is_restaurant_public(
  target_restaurant_id bigint
)

returns boolean

language sql
stable
security definer

set search_path = ''

as $$

  select exists (

    select 1

    from public.restaurants r

    where r.id = target_restaurant_id

      and r.is_active = true

      and public.is_provider_approved(
        r.owner_id,
        'restaurant'
      )

  );

$$;


revoke all
on function public.is_restaurant_public(bigint)
from public;

grant execute
on function public.is_restaurant_public(bigint)
to anon, authenticated;



-- =========================================================
-- 7. ENABLE RLS ON RESTAURANTS
-- =========================================================

alter table public.restaurants
enable row level security;



-- =========================================================
-- 8. PUBLIC/TRAVELERS CAN VIEW APPROVED ACTIVE RESTAURANTS
-- =========================================================

drop policy if exists
"Public can view approved active restaurants"
on public.restaurants;

create policy
"Public can view approved active restaurants"
on public.restaurants

for select
to anon, authenticated

using (

  is_active = true

  and public.is_provider_approved(
    owner_id,
    'restaurant'
  )

);



-- =========================================================
-- 9. OWNER CAN VIEW OWN RESTAURANTS
-- Even while pending/inactive
-- =========================================================

drop policy if exists
"Restaurant owners can view own restaurants"
on public.restaurants;

create policy
"Restaurant owners can view own restaurants"
on public.restaurants

for select
to authenticated

using (
  owner_id = auth.uid()
);



-- =========================================================
-- 10. RESTAURANT OWNER CAN CREATE OWN RESTAURANT
-- =========================================================

drop policy if exists
"Restaurant owners can create restaurants"
on public.restaurants;

create policy
"Restaurant owners can create restaurants"
on public.restaurants

for insert
to authenticated

with check (

  owner_id = auth.uid()

  and exists (

    select 1

    from public.profiles p

    where p.id = auth.uid()

      and p.role = 'restaurant_owner'

  )

);



-- =========================================================
-- 11. OWNER CAN UPDATE OWN RESTAURANT
-- =========================================================

drop policy if exists
"Restaurant owners can update own restaurants"
on public.restaurants;

create policy
"Restaurant owners can update own restaurants"
on public.restaurants

for update
to authenticated

using (
  owner_id = auth.uid()
)

with check (

  owner_id = auth.uid()

  and exists (

    select 1

    from public.profiles p

    where p.id = auth.uid()

      and p.role = 'restaurant_owner'

  )

);



-- =========================================================
-- 12. OWNER CAN DELETE OWN RESTAURANT
-- =========================================================

drop policy if exists
"Restaurant owners can delete own restaurants"
on public.restaurants;

create policy
"Restaurant owners can delete own restaurants"
on public.restaurants

for delete
to authenticated

using (

  owner_id = auth.uid()

  and exists (

    select 1

    from public.profiles p

    where p.id = auth.uid()

      and p.role = 'restaurant_owner'

  )

);
