-- =========================================================
-- TripMate
-- Migration 005: Accommodation Marketplace Module
-- =========================================================


-- =========================================================
-- 1. ACCOMMODATION TYPES
-- =========================================================

create table if not exists public.accommodation_types (
  id bigint generated by default as identity primary key,
  name text unique not null,
  is_active boolean not null default true
);


-- =========================================================
-- 2. ACCOMMODATIONS / PROPERTIES
-- =========================================================

create table if not exists public.accommodations (
  id bigint generated by default as identity primary key,

  owner_id uuid not null
    references public.profiles(id)
    on delete cascade,

  accommodation_type_id bigint
    references public.accommodation_types(id)
    on delete set null,

  name text not null,
  description text,

  address text not null,
  latitude numeric(9,6),
  longitude numeric(9,6),

  phone text,
  email text,
  website_url text,

  check_in_time time,
  check_out_time time,

  star_rating numeric(2,1),

  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (
    star_rating is null
    or star_rating between 0 and 5
  )
);


-- =========================================================
-- 3. PROPERTY IMAGES
-- =========================================================

create table if not exists public.accommodation_images (
  id bigint generated by default as identity primary key,

  accommodation_id bigint not null
    references public.accommodations(id)
    on delete cascade,

  image_url text not null,

  image_type text not null default 'gallery'
    check (
      image_type in (
        'cover',
        'gallery',
        'exterior',
        'interior',
        'facility'
      )
    ),

  display_order integer not null default 0,

  created_at timestamptz not null default now()
);


-- =========================================================
-- 4. PROPERTY AMENITY CATALOG
-- =========================================================

create table if not exists public.accommodation_amenity_catalog (
  id bigint generated by default as identity primary key,

  name text unique not null,

  category text not null
    check (
      category in (
        'general',
        'food',
        'wellness',
        'transport',
        'family',
        'business',
        'accessibility',
        'safety'
      )
    ),

  is_active boolean not null default true
);


create table if not exists public.accommodation_amenities (
  accommodation_id bigint not null
    references public.accommodations(id)
    on delete cascade,

  amenity_id bigint not null
    references public.accommodation_amenity_catalog(id)
    on delete cascade,

  details text,

  primary key (accommodation_id, amenity_id)
);


-- =========================================================
-- 5. ROOM TYPES
-- =========================================================

create table if not exists public.room_types (
  id bigint generated by default as identity primary key,

  accommodation_id bigint not null
    references public.accommodations(id)
    on delete cascade,

  name text not null,
  description text,

  max_adults integer not null default 1,
  max_children integer not null default 0,
  max_guests integer not null,

  room_size_square_meters numeric(8,2),

  base_price_per_night numeric(12,2) not null,
  currency text not null default 'LKR',

  total_rooms integer not null,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (max_adults > 0),
  check (max_children >= 0),
  check (max_guests > 0),
  check (max_guests >= max_adults),
  check (base_price_per_night >= 0),
  check (total_rooms > 0),

  unique (accommodation_id, name)
);


-- =========================================================
-- 6. ROOM IMAGES
-- =========================================================

create table if not exists public.room_images (
  id bigint generated by default as identity primary key,

  room_type_id bigint not null
    references public.room_types(id)
    on delete cascade,

  image_url text not null,

  display_order integer not null default 0,

  created_at timestamptz not null default now()
);


-- =========================================================
-- 7. ROOM AMENITY CATALOG
-- =========================================================

create table if not exists public.room_amenity_catalog (
  id bigint generated by default as identity primary key,

  name text unique not null,

  category text not null default 'general',

  is_active boolean not null default true
);


create table if not exists public.room_amenities (
  room_type_id bigint not null
    references public.room_types(id)
    on delete cascade,

  amenity_id bigint not null
    references public.room_amenity_catalog(id)
    on delete cascade,

  details text,

  primary key (room_type_id, amenity_id)
);


-- =========================================================
-- 8. BED TYPES
-- =========================================================

create table if not exists public.bed_types (
  id bigint generated by default as identity primary key,

  name text unique not null,

  is_active boolean not null default true
);


create table if not exists public.room_beds (
  id bigint generated by default as identity primary key,

  room_type_id bigint not null
    references public.room_types(id)
    on delete cascade,

  bed_type_id bigint not null
    references public.bed_types(id)
    on delete restrict,

  quantity integer not null,

  check (quantity > 0),

  unique (room_type_id, bed_type_id)
);


-- =========================================================
-- 9. MEAL PLANS
-- =========================================================

create table if not exists public.meal_plans (
  id bigint generated by default as identity primary key,

  name text unique not null,

  description text,

  is_active boolean not null default true
);


create table if not exists public.accommodation_meal_plans (
  id bigint generated by default as identity primary key,

  accommodation_id bigint not null
    references public.accommodations(id)
    on delete cascade,

  meal_plan_id bigint not null
    references public.meal_plans(id)
    on delete restrict,

  price_per_adult numeric(12,2) not null default 0,
  price_per_child numeric(12,2) not null default 0,

  currency text not null default 'LKR',

  is_available boolean not null default true,

  check (price_per_adult >= 0),
  check (price_per_child >= 0),

  unique (accommodation_id, meal_plan_id)
);


-- =========================================================
-- 10. DATE-BASED ROOM INVENTORY + PRICING
-- =========================================================

create table if not exists public.room_availability (
  id bigint generated by default as identity primary key,

  room_type_id bigint not null
    references public.room_types(id)
    on delete cascade,

  date date not null,

  available_rooms integer not null,

  price_override numeric(12,2),

  minimum_stay_nights integer not null default 1,

  is_closed boolean not null default false,

  created_at timestamptz not null default now(),

  check (available_rooms >= 0),

  check (
    price_override is null
    or price_override >= 0
  ),

  check (minimum_stay_nights > 0),

  unique (room_type_id, date)
);


-- =========================================================
-- 11. PREVENT INVENTORY ABOVE TOTAL ROOM COUNT
-- =========================================================

create or replace function public.validate_room_inventory()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  room_limit integer;
begin

  select total_rooms
  into room_limit
  from public.room_types
  where id = new.room_type_id;

  if room_limit is null then
    raise exception 'Invalid room type';
  end if;

  if new.available_rooms > room_limit then
    raise exception
      'Available rooms cannot exceed total room count';
  end if;

  return new;
end;
$$;


drop trigger if exists validate_room_inventory_trigger
on public.room_availability;

create trigger validate_room_inventory_trigger
before insert or update
on public.room_availability
for each row
execute procedure public.validate_room_inventory();


-- =========================================================
-- 12. ACCOMMODATION OFFERS
-- =========================================================

create table if not exists public.accommodation_offers (
  id bigint generated by default as identity primary key,

  accommodation_id bigint not null
    references public.accommodations(id)
    on delete cascade,

  room_type_id bigint
    references public.room_types(id)
    on delete cascade,

  title text not null,
  description text,

  offer_type text not null
    check (
      offer_type in (
        'percentage',
        'fixed_amount',
        'special_price',
        'package'
      )
    ),

  discount_value numeric(12,2),

  minimum_nights integer,

  start_date date,
  end_date date,

  terms_and_conditions text,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),

  check (
    discount_value is null
    or discount_value >= 0
  ),

  check (
    minimum_nights is null
    or minimum_nights > 0
  ),

  check (
    end_date is null
    or start_date is null
    or end_date >= start_date
  )
);


-- =========================================================
-- 13. PROPERTY POLICIES
-- =========================================================

create table if not exists public.accommodation_policies (
  id bigint generated by default as identity primary key,

  accommodation_id bigint unique not null
    references public.accommodations(id)
    on delete cascade,

  cancellation_policy text,

  children_policy text,

  pet_policy text,

  smoking_policy text,

  minimum_check_in_age integer,

  damage_deposit numeric(12,2),

  additional_rules text,

  updated_at timestamptz not null default now(),

  check (
    minimum_check_in_age is null
    or minimum_check_in_age >= 0
  ),

  check (
    damage_deposit is null
    or damage_deposit >= 0
  )
);


-- =========================================================
-- 14. PROPERTY TEMPORARY CLOSURES / OVERRIDES
-- =========================================================

create table if not exists public.accommodation_availability (
  id bigint generated by default as identity primary key,

  accommodation_id bigint not null
    references public.accommodations(id)
    on delete cascade,

  date date not null,

  is_available boolean not null default true,

  reason text,

  unique (accommodation_id, date)
);


-- =========================================================
-- 15. INDEXES
-- =========================================================

create index if not exists idx_accommodations_owner_id
on public.accommodations(owner_id);

create index if not exists idx_accommodations_type
on public.accommodations(accommodation_type_id);

create index if not exists idx_accommodations_location
on public.accommodations(latitude, longitude);

create index if not exists idx_room_types_accommodation
on public.room_types(accommodation_id);

create index if not exists idx_room_availability_room_date
on public.room_availability(room_type_id, date);

create index if not exists idx_accommodation_offers_property
on public.accommodation_offers(accommodation_id);


-- =========================================================
-- 16. AUTO UPDATE updated_at
-- =========================================================

drop trigger if exists set_accommodations_updated_at
on public.accommodations;

create trigger set_accommodations_updated_at
before update on public.accommodations
for each row
execute procedure public.set_updated_at();


drop trigger if exists set_room_types_updated_at
on public.room_types;

create trigger set_room_types_updated_at
before update on public.room_types
for each row
execute procedure public.set_updated_at();


drop trigger if exists set_accommodation_policies_updated_at
on public.accommodation_policies;

create trigger set_accommodation_policies_updated_at
before update on public.accommodation_policies
for each row
execute procedure public.set_updated_at();


-- =========================================================
-- 17. DEFAULT ACCOMMODATION TYPES
-- =========================================================

insert into public.accommodation_types (name)
values
  ('Hotel'),
  ('Resort'),
  ('Villa'),
  ('Guest House'),
  ('Apartment'),
  ('Hostel'),
  ('Homestay')
on conflict (name)
do nothing;


-- =========================================================
-- 18. DEFAULT PROPERTY AMENITIES
-- =========================================================

insert into public.accommodation_amenity_catalog (
  name,
  category
)
values
  ('Wi-Fi', 'general'),
  ('Parking', 'general'),
  ('Air Conditioning', 'general'),
  ('Swimming Pool', 'wellness'),
  ('Gym', 'wellness'),
  ('Spa', 'wellness'),
  ('Restaurant', 'food'),
  ('Room Service', 'food'),
  ('Airport Transfer', 'transport'),
  ('Shuttle Service', 'transport'),
  ('Kids Area', 'family'),
  ('Business Center', 'business'),
  ('Wheelchair Access', 'accessibility'),
  ('24-Hour Security', 'safety')
on conflict (name)
do nothing;


-- =========================================================
-- 19. DEFAULT ROOM AMENITIES
-- =========================================================

insert into public.room_amenity_catalog (
  name,
  category
)
values
  ('Private Bathroom', 'bathroom'),
  ('Hot Water', 'bathroom'),
  ('TV', 'entertainment'),
  ('Wi-Fi', 'connectivity'),
  ('Air Conditioning', 'comfort'),
  ('Balcony', 'outdoor'),
  ('Mini Bar', 'food'),
  ('Refrigerator', 'food'),
  ('Safe', 'security'),
  ('Hair Dryer', 'bathroom'),
  ('Work Desk', 'workspace'),
  ('Sea View', 'view'),
  ('Mountain View', 'view'),
  ('City View', 'view')
on conflict (name)
do nothing;


-- =========================================================
-- 20. DEFAULT BED TYPES
-- =========================================================

insert into public.bed_types (name)
values
  ('Single Bed'),
  ('Double Bed'),
  ('Queen Bed'),
  ('King Bed'),
  ('Bunk Bed'),
  ('Sofa Bed')
on conflict (name)
do nothing;


-- =========================================================
-- 21. DEFAULT MEAL PLANS
-- =========================================================

insert into public.meal_plans (
  name,
  description
)
values
  ('Room Only', 'Accommodation without meals'),
  ('Breakfast Included', 'Room with breakfast'),
  ('Half Board', 'Breakfast and one main meal'),
  ('Full Board', 'Breakfast, lunch and dinner')
on conflict (name)
do nothing;
