-- =========================================================
-- TripMate
-- Migration 009: Traveler Core, Attractions & Trip Cart
-- =========================================================


-- =========================================================
-- 1. REFINE EXISTING TRIPS TABLE
-- =========================================================

alter table public.trips
  add column if not exists adult_count integer,
  add column if not exists child_count integer,
  add column if not exists currency text not null default 'LKR',
  add column if not exists special_requirements text,
  add column if not exists updated_at timestamptz not null default now();


-- Backfill existing trips safely
update public.trips
set
  adult_count = number_of_travelers,
  child_count = 0
where adult_count is null
   or child_count is null;


alter table public.trips
  alter column adult_count set default 1,
  alter column adult_count set not null,
  alter column child_count set default 0,
  alter column child_count set not null;


-- Trip date validation
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'trips_date_range_check'
  ) then

    alter table public.trips
      add constraint trips_date_range_check
      check (end_date >= start_date);

  end if;
end $$;


-- Adult validation
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'trips_adult_count_check'
  ) then

    alter table public.trips
      add constraint trips_adult_count_check
      check (adult_count > 0);

  end if;
end $$;


-- Child validation
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'trips_child_count_check'
  ) then

    alter table public.trips
      add constraint trips_child_count_check
      check (child_count >= 0);

  end if;
end $$;



-- =========================================================
-- 2. KEEP TOTAL TRAVELER COUNT CONSISTENT
-- =========================================================

create or replace function public.sync_trip_traveler_count()
returns trigger
language plpgsql
as $$
begin

  new.number_of_travelers :=
    new.adult_count + new.child_count;

  return new;

end;
$$;


drop trigger if exists sync_trip_traveler_count_trigger
on public.trips;

create trigger sync_trip_traveler_count_trigger
before insert or update
on public.trips
for each row
execute procedure public.sync_trip_traveler_count();



-- =========================================================
-- 3. UPDATED_AT FOR TRIPS
-- =========================================================

drop trigger if exists set_trips_updated_at
on public.trips;

create trigger set_trips_updated_at
before update on public.trips
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 4. TRIP PREFERENCES
-- Flexible data useful for AI recommendations.
-- =========================================================

create table if not exists public.trip_preferences (
  id bigint generated by default as identity primary key,

  trip_id bigint unique not null
    references public.trips(id)
    on delete cascade,

  interests jsonb not null default '[]'::jsonb,

  food_preferences jsonb not null default '[]'::jsonb,

  dietary_preferences jsonb not null default '[]'::jsonb,

  accommodation_preferences jsonb not null default '{}'::jsonb,

  transport_preferences jsonb not null default '{}'::jsonb,

  notes text,

  updated_at timestamptz not null default now()
);


drop trigger if exists set_trip_preferences_updated_at
on public.trip_preferences;

create trigger set_trip_preferences_updated_at
before update on public.trip_preferences
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 5. REFINE DESTINATIONS
-- =========================================================

alter table public.destinations
  add column if not exists province text,
  add column if not exists is_active boolean not null default true,
  add column if not exists updated_at timestamptz not null default now();


drop trigger if exists set_destinations_updated_at
on public.destinations;

create trigger set_destinations_updated_at
before update on public.destinations
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 6. REFINE TRIP DESTINATIONS
-- =========================================================

alter table public.trip_destinations
  add column if not exists planned_arrival_date date,
  add column if not exists planned_departure_date date,
  add column if not exists notes text;


-- Validate destination dates against the parent trip
create or replace function public.validate_trip_destination_dates()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  trip_start date;
  trip_end date;
begin

  select
    start_date,
    end_date
  into
    trip_start,
    trip_end
  from public.trips
  where id = new.trip_id;


  if trip_start is null then
    raise exception 'Invalid trip';
  end if;


  if new.planned_arrival_date is not null
     and (
       new.planned_arrival_date < trip_start
       or new.planned_arrival_date > trip_end
     )
  then
    raise exception
      'Destination arrival date must be within trip dates';
  end if;


  if new.planned_departure_date is not null
     and (
       new.planned_departure_date < trip_start
       or new.planned_departure_date > trip_end
     )
  then
    raise exception
      'Destination departure date must be within trip dates';
  end if;


  if new.planned_arrival_date is not null
     and new.planned_departure_date is not null
     and new.planned_departure_date
         < new.planned_arrival_date
  then
    raise exception
      'Destination departure date cannot be before arrival date';
  end if;


  return new;

end;
$$;


drop trigger if exists validate_trip_destination_dates_trigger
on public.trip_destinations;

create trigger validate_trip_destination_dates_trigger
before insert or update
on public.trip_destinations
for each row
execute procedure public.validate_trip_destination_dates();



-- =========================================================
-- 7. ATTRACTION CATEGORIES
-- =========================================================

create table if not exists public.attraction_categories (
  id bigint generated by default as identity primary key,

  name text unique not null,

  is_active boolean not null default true
);



-- =========================================================
-- 8. ATTRACTIONS
-- =========================================================

create table if not exists public.attractions (
  id bigint generated by default as identity primary key,

  destination_id bigint not null
    references public.destinations(id)
    on delete cascade,

  category_id bigint
    references public.attraction_categories(id)
    on delete set null,

  name text not null,

  description text,

  address text,

  latitude numeric(9,6),
  longitude numeric(9,6),

  entrance_fee numeric(12,2) not null default 0,

  currency text not null default 'LKR',

  recommended_duration_minutes integer,

  booking_required boolean not null default false,

  accessibility_notes text,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (entrance_fee >= 0),

  check (
    recommended_duration_minutes is null
    or recommended_duration_minutes > 0
  )
);


drop trigger if exists set_attractions_updated_at
on public.attractions;

create trigger set_attractions_updated_at
before update on public.attractions
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 9. ATTRACTION IMAGES
-- =========================================================

create table if not exists public.attraction_images (
  id bigint generated by default as identity primary key,

  attraction_id bigint not null
    references public.attractions(id)
    on delete cascade,

  image_url text not null,

  image_type text not null default 'gallery'
    check (
      image_type in (
        'cover',
        'gallery'
      )
    ),

  display_order integer not null default 0
);



-- =========================================================
-- 10. ATTRACTION OPENING HOURS
-- =========================================================

create table if not exists public.attraction_opening_hours (
  id bigint generated by default as identity primary key,

  attraction_id bigint not null
    references public.attractions(id)
    on delete cascade,

  day_of_week integer not null
    check (day_of_week between 0 and 6),

  opening_time time,

  closing_time time,

  is_closed boolean not null default false,

  unique (attraction_id, day_of_week)
);



-- =========================================================
-- 11. ACTIVITIES
-- =========================================================

create table if not exists public.activities (
  id bigint generated by default as identity primary key,

  destination_id bigint not null
    references public.destinations(id)
    on delete cascade,

  attraction_id bigint
    references public.attractions(id)
    on delete set null,

  name text not null,

  description text,

  price_per_person numeric(12,2) not null default 0,

  currency text not null default 'LKR',

  duration_minutes integer,

  minimum_participants integer not null default 1,

  maximum_participants integer,

  minimum_age integer,

  difficulty_level text
    check (
      difficulty_level is null
      or difficulty_level in (
        'easy',
        'moderate',
        'hard'
      )
    ),

  booking_required boolean not null default true,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (price_per_person >= 0),

  check (
    duration_minutes is null
    or duration_minutes > 0
  ),

  check (minimum_participants > 0),

  check (
    maximum_participants is null
    or maximum_participants >= minimum_participants
  ),

  check (
    minimum_age is null
    or minimum_age >= 0
  )
);


drop trigger if exists set_activities_updated_at
on public.activities;

create trigger set_activities_updated_at
before update on public.activities
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 12. ACTIVITY AVAILABILITY
-- =========================================================

create table if not exists public.activity_availability (
  id bigint generated by default as identity primary key,

  activity_id bigint not null
    references public.activities(id)
    on delete cascade,

  date date not null,

  start_time time,

  end_time time,

  available_slots integer,

  price_override numeric(12,2),

  is_available boolean not null default true,

  check (
    available_slots is null
    or available_slots >= 0
  ),

  check (
    price_override is null
    or price_override >= 0
  ),

  check (
    end_time is null
    or start_time is null
    or end_time > start_time
  ),

  unique (
    activity_id,
    date,
    start_time
  )
);



-- =========================================================
-- 13. TRIP CART
-- =========================================================

create table if not exists public.trip_cart_items (
  id bigint generated by default as identity primary key,

  trip_id bigint not null
    references public.trips(id)
    on delete cascade,

  item_type text not null
    check (
      item_type in (
        'room',
        'food',
        'buffet',
        'restaurant_reservation',
        'attraction',
        'activity'
      )
    ),

  room_type_id bigint
    references public.room_types(id)
    on delete cascade,

  food_item_id bigint
    references public.food_items(id)
    on delete cascade,

  buffet_package_id bigint
    references public.buffet_packages(id)
    on delete cascade,

  restaurant_id bigint
    references public.restaurants(id)
    on delete cascade,

  attraction_id bigint
    references public.attractions(id)
    on delete cascade,

  activity_id bigint
    references public.activities(id)
    on delete cascade,

  item_name_snapshot text not null,

  unit_price_snapshot numeric(12,2) not null default 0,

  currency text not null default 'LKR',

  quantity integer not null default 1,

  service_date date,

  service_start_time time,

  service_end_time time,

  selection_details jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),

  check (unit_price_snapshot >= 0),

  check (quantity > 0),

  check (
    service_end_time is null
    or service_start_time is null
    or service_end_time > service_start_time
  )
);



-- =========================================================
-- 14. VALIDATE TRIP CART SERVICE SOURCE
-- Exactly one correct source must match item_type.
-- =========================================================

create or replace function public.validate_trip_cart_item()
returns trigger
language plpgsql
as $$
begin

  if new.item_type = 'room' then

    if new.room_type_id is null
       or new.food_item_id is not null
       or new.buffet_package_id is not null
       or new.restaurant_id is not null
       or new.attraction_id is not null
       or new.activity_id is not null
    then
      raise exception 'Invalid source for room cart item';
    end if;


  elsif new.item_type = 'food' then

    if new.food_item_id is null
       or new.room_type_id is not null
       or new.buffet_package_id is not null
       or new.restaurant_id is not null
       or new.attraction_id is not null
       or new.activity_id is not null
    then
      raise exception 'Invalid source for food cart item';
    end if;


  elsif new.item_type = 'buffet' then

    if new.buffet_package_id is null
       or new.room_type_id is not null
       or new.food_item_id is not null
       or new.restaurant_id is not null
       or new.attraction_id is not null
       or new.activity_id is not null
    then
      raise exception 'Invalid source for buffet cart item';
    end if;


  elsif new.item_type = 'restaurant_reservation' then

    if new.restaurant_id is null
       or new.room_type_id is not null
       or new.food_item_id is not null
       or new.buffet_package_id is not null
       or new.attraction_id is not null
       or new.activity_id is not null
    then
      raise exception
        'Invalid source for restaurant reservation';
    end if;


  elsif new.item_type = 'attraction' then

    if new.attraction_id is null
       or new.room_type_id is not null
       or new.food_item_id is not null
       or new.buffet_package_id is not null
       or new.restaurant_id is not null
       or new.activity_id is not null
    then
      raise exception 'Invalid source for attraction cart item';
    end if;


  elsif new.item_type = 'activity' then

    if new.activity_id is null
       or new.room_type_id is not null
       or new.food_item_id is not null
       or new.buffet_package_id is not null
       or new.restaurant_id is not null
       or new.attraction_id is not null
    then
      raise exception 'Invalid source for activity cart item';
    end if;

  end if;


  return new;

end;
$$;


drop trigger if exists validate_trip_cart_item_trigger
on public.trip_cart_items;

create trigger validate_trip_cart_item_trigger
before insert or update
on public.trip_cart_items
for each row
execute procedure public.validate_trip_cart_item();



-- =========================================================
-- 15. CART DUPLICATE PREVENTION
-- Same service should update quantity/details instead of
-- creating unnecessary duplicate rows.
-- =========================================================

create unique index if not exists
idx_trip_cart_unique_room
on public.trip_cart_items (
  trip_id,
  room_type_id
)
where item_type = 'room';


create unique index if not exists
idx_trip_cart_unique_food
on public.trip_cart_items (
  trip_id,
  food_item_id
)
where item_type = 'food';


create unique index if not exists
idx_trip_cart_unique_buffet
on public.trip_cart_items (
  trip_id,
  buffet_package_id
)
where item_type = 'buffet';


create unique index if not exists
idx_trip_cart_unique_restaurant_reservation
on public.trip_cart_items (
  trip_id,
  restaurant_id
)
where item_type = 'restaurant_reservation';


create unique index if not exists
idx_trip_cart_unique_attraction
on public.trip_cart_items (
  trip_id,
  attraction_id
)
where item_type = 'attraction';


create unique index if not exists
idx_trip_cart_unique_activity
on public.trip_cart_items (
  trip_id,
  activity_id
)
where item_type = 'activity';



-- =========================================================
-- 16. PERFORMANCE INDEXES
-- =========================================================

create index if not exists idx_trips_traveler_id
on public.trips(traveler_id);

create index if not exists idx_trip_destinations_trip_id
on public.trip_destinations(trip_id);

create index if not exists idx_attractions_destination_id
on public.attractions(destination_id);

create index if not exists idx_activities_destination_id
on public.activities(destination_id);

create index if not exists idx_activity_availability_date
on public.activity_availability(activity_id, date);

create index if not exists idx_trip_cart_trip_id
on public.trip_cart_items(trip_id);



-- =========================================================
-- 17. DEFAULT ATTRACTION CATEGORIES
-- =========================================================

insert into public.attraction_categories (name)
values
  ('Nature'),
  ('Historical'),
  ('Cultural'),
  ('Religious'),
  ('Beach'),
  ('Wildlife'),
  ('Adventure'),
  ('Viewpoint'),
  ('Museum'),
  ('Park'),
  ('Waterfall'),
  ('Shopping')
on conflict (name)
do nothing;
