-- =========================================================
-- TripMate
-- Migration 014: Driver, Vehicle and Transport Bidding Core
-- =========================================================


-- =========================================================
-- 1. DRIVER PROFILE
-- =========================================================

create table if not exists public.driver_profiles (
  user_id uuid primary key
    references public.profiles(id)
    on delete cascade,

  public_name text not null,
  bio text,

  years_experience integer not null default 0
    check (years_experience >= 0),

  is_accepting_requests boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- Only users with role = driver can have a driver profile
create or replace function public.validate_driver_profile_role()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  profile_role text;
begin

  select p.role
  into profile_role
  from public.profiles p
  where p.id = new.user_id;

  if profile_role is distinct from 'driver' then
    raise exception 'Only users with driver role can create a driver profile';
  end if;

  return new;
end;
$$;


drop trigger if exists validate_driver_profile_role_trigger
on public.driver_profiles;

create trigger validate_driver_profile_role_trigger
before insert or update
on public.driver_profiles
for each row
execute procedure public.validate_driver_profile_role();


drop trigger if exists set_driver_profiles_updated_at
on public.driver_profiles;

create trigger set_driver_profiles_updated_at
before update
on public.driver_profiles
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 2. DRIVER LICENCE DETAILS
-- Private information - not intended for public browsing
-- =========================================================

create table if not exists public.driver_licenses (
  id bigint generated by default as identity primary key,

  driver_id uuid not null unique
    references public.driver_profiles(user_id)
    on delete cascade,

  license_number text not null,
  license_class text,

  issued_date date,
  expiry_date date not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (
    issued_date is null
    or expiry_date >= issued_date
  )
);


create unique index if not exists driver_license_number_unique_idx
on public.driver_licenses (lower(license_number));


drop trigger if exists set_driver_licenses_updated_at
on public.driver_licenses;

create trigger set_driver_licenses_updated_at
before update
on public.driver_licenses
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 3. DRIVER DOCUMENTS
-- =========================================================

create table if not exists public.driver_documents (
  id bigint generated by default as identity primary key,

  driver_id uuid not null
    references public.driver_profiles(user_id)
    on delete cascade,

  document_type text not null
    check (
      document_type in (
        'driving_license',
        'nic',
        'passport',
        'profile_photo',
        'other'
      )
    ),

  storage_path text not null,

  expiry_date date,

  verification_status text not null default 'pending'
    check (
      verification_status in (
        'pending',
        'approved',
        'rejected'
      )
    ),

  review_notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


drop trigger if exists set_driver_documents_updated_at
on public.driver_documents;

create trigger set_driver_documents_updated_at
before update
on public.driver_documents
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 4. VEHICLE TYPES
-- =========================================================

create table if not exists public.vehicle_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text
);


insert into public.vehicle_types (name)
values
  ('Car'),
  ('SUV'),
  ('Van'),
  ('Minivan'),
  ('Minibus')
on conflict (name) do nothing;



-- =========================================================
-- 5. VEHICLES
-- passenger_capacity excludes the driver
-- =========================================================

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,

  driver_id uuid not null
    references public.driver_profiles(user_id)
    on delete cascade,

  vehicle_type_id bigint not null
    references public.vehicle_types(id)
    on delete restrict,

  registration_number text not null,

  make text not null,
  model text not null,

  manufacture_year integer
    check (
      manufacture_year is null
      or manufacture_year between 1980 and 2100
    ),

  color text,

  passenger_capacity integer not null
    check (passenger_capacity > 0),

  luggage_capacity integer not null default 0
    check (luggage_capacity >= 0),

  description text,

  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create unique index if not exists vehicle_registration_unique_idx
on public.vehicles (lower(registration_number));


create index if not exists vehicles_driver_idx
on public.vehicles(driver_id);


drop trigger if exists set_vehicles_updated_at
on public.vehicles;

create trigger set_vehicles_updated_at
before update
on public.vehicles
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 6. VEHICLE VERIFICATION
-- Separated from vehicles so a driver cannot simply set
-- their own vehicle as "approved".
-- =========================================================

create table if not exists public.vehicle_verifications (
  vehicle_id bigint primary key
    references public.vehicles(id)
    on delete cascade,

  status text not null default 'pending'
    check (
      status in (
        'pending',
        'approved',
        'rejected',
        'suspended'
      )
    ),

  submitted_at timestamptz not null default now(),

  reviewed_by uuid
    references public.profiles(id)
    on delete set null,

  reviewed_at timestamptz,

  review_notes text
);


create or replace function public.create_vehicle_verification()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin

  insert into public.vehicle_verifications (
    vehicle_id,
    status
  )
  values (
    new.id,
    'pending'
  )
  on conflict (vehicle_id) do nothing;

  return new;
end;
$$;


drop trigger if exists create_vehicle_verification_trigger
on public.vehicles;

create trigger create_vehicle_verification_trigger
after insert
on public.vehicles
for each row
execute procedure public.create_vehicle_verification();



-- =========================================================
-- 7. VEHICLE IMAGES
-- =========================================================

create table if not exists public.vehicle_images (
  id bigint generated by default as identity primary key,

  vehicle_id bigint not null
    references public.vehicles(id)
    on delete cascade,

  image_url text not null,

  is_primary boolean not null default false,

  created_at timestamptz not null default now()
);


create index if not exists vehicle_images_vehicle_idx
on public.vehicle_images(vehicle_id);



-- =========================================================
-- 8. VEHICLE FEATURES
-- =========================================================

create table if not exists public.vehicle_feature_catalog (
  id bigint generated by default as identity primary key,
  name text not null unique
);


insert into public.vehicle_feature_catalog (name)
values
  ('Air Conditioning'),
  ('Wi-Fi'),
  ('Charging Ports'),
  ('Child Seat'),
  ('Wheelchair Accessible'),
  ('Large Luggage Space'),
  ('Roof Rack')
on conflict (name) do nothing;


create table if not exists public.vehicle_features (
  vehicle_id bigint not null
    references public.vehicles(id)
    on delete cascade,

  feature_id bigint not null
    references public.vehicle_feature_catalog(id)
    on delete cascade,

  primary key (vehicle_id, feature_id)
);



-- =========================================================
-- 9. VEHICLE DOCUMENTS
-- =========================================================

create table if not exists public.vehicle_documents (
  id bigint generated by default as identity primary key,

  vehicle_id bigint not null
    references public.vehicles(id)
    on delete cascade,

  document_type text not null
    check (
      document_type in (
        'registration',
        'insurance',
        'revenue_license',
        'inspection',
        'other'
      )
    ),

  storage_path text not null,

  expiry_date date,

  verification_status text not null default 'pending'
    check (
      verification_status in (
        'pending',
        'approved',
        'rejected'
      )
    ),

  review_notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


drop trigger if exists set_vehicle_documents_updated_at
on public.vehicle_documents;

create trigger set_vehicle_documents_updated_at
before update
on public.vehicle_documents
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 10. DRIVER AVAILABILITY
-- =========================================================

create table if not exists public.driver_availability (
  id bigint generated by default as identity primary key,

  driver_id uuid not null
    references public.driver_profiles(user_id)
    on delete cascade,

  availability_date date not null,

  is_all_day boolean not null default true,

  start_time time,
  end_time time,

  status text not null default 'available'
    check (
      status in (
        'available',
        'unavailable',
        'booked'
      )
    ),

  notes text,

  created_at timestamptz not null default now(),

  check (
    (
      is_all_day = true
      and start_time is null
      and end_time is null
    )
    or
    (
      is_all_day = false
      and start_time is not null
      and end_time is not null
      and end_time > start_time
    )
  )
);


create unique index if not exists driver_availability_all_day_unique_idx
on public.driver_availability(driver_id, availability_date)
where is_all_day = true;


create unique index if not exists driver_availability_time_unique_idx
on public.driver_availability(
  driver_id,
  availability_date,
  start_time,
  end_time
)
where is_all_day = false;


create index if not exists driver_availability_lookup_idx
on public.driver_availability(
  driver_id,
  availability_date
);



-- =========================================================
-- 11. TRANSPORT REQUEST
-- Snapshot values protect the request from later trip edits.
-- =========================================================

create table if not exists public.transport_requests (
  id bigint generated by default as identity primary key,

  trip_id bigint not null
    references public.trips(id)
    on delete cascade,

  traveler_id uuid not null
    references public.profiles(id)
    on delete cascade,

  pickup_location_snapshot text not null,

  pickup_latitude numeric(9,6),
  pickup_longitude numeric(9,6),

  trip_start_date date not null,
  trip_end_date date not null,

  passenger_count integer not null
    check (passenger_count > 0),

  luggage_count integer not null default 0
    check (luggage_count >= 0),

  special_requirements text,

  route_distance_km numeric(10,2)
    check (
      route_distance_km is null
      or route_distance_km > 0
    ),

  estimated_duration_minutes integer
    check (
      estimated_duration_minutes is null
      or estimated_duration_minutes > 0
    ),

  currency text not null default 'LKR',

  bidding_deadline timestamptz,

  status text not null default 'draft'
    check (
      status in (
        'draft',
        'open',
        'driver_selected',
        'expired',
        'cancelled',
        'completed'
      )
    ),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (trip_end_date >= trip_start_date)
);


create index if not exists transport_requests_trip_idx
on public.transport_requests(trip_id);


create index if not exists transport_requests_traveler_idx
on public.transport_requests(traveler_id);


create index if not exists transport_requests_status_idx
on public.transport_requests(status);


-- Only one active transport-request cycle for a trip
create unique index if not exists one_active_transport_request_per_trip_idx
on public.transport_requests(trip_id)
where status in (
  'draft',
  'open',
  'driver_selected'
);


drop trigger if exists set_transport_requests_updated_at
on public.transport_requests;

create trigger set_transport_requests_updated_at
before update
on public.transport_requests
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 12. COPY AUTHORITATIVE TRIP DATA INTO REQUEST SNAPSHOT
-- =========================================================

create or replace function public.populate_transport_request_snapshot()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  trip_record record;
begin

  if tg_op = 'UPDATE'
     and new.trip_id is distinct from old.trip_id then
    raise exception 'Transport request trip cannot be changed';
  end if;


  if tg_op = 'INSERT' then

    select
      t.traveler_id,
      t.start_location,
      t.start_lat,
      t.start_lng,
      t.start_date,
      t.end_date,
      t.number_of_travelers,
      t.special_requirements,
      t.currency
    into trip_record
    from public.trips t
    where t.id = new.trip_id;


    if not found then
      raise exception 'Trip does not exist';
    end if;


    if not exists (
      select 1
      from public.trip_destinations td
      where td.trip_id = new.trip_id
    ) then
      raise exception 'Trip must contain at least one destination before requesting transport';
    end if;


    new.traveler_id :=
      trip_record.traveler_id;

    new.pickup_location_snapshot :=
      trip_record.start_location;

    new.pickup_latitude :=
      trip_record.start_lat;

    new.pickup_longitude :=
      trip_record.start_lng;

    new.trip_start_date :=
      trip_record.start_date;

    new.trip_end_date :=
      trip_record.end_date;

    new.passenger_count :=
      trip_record.number_of_travelers;

    new.special_requirements :=
      trip_record.special_requirements;

    new.currency :=
      coalesce(trip_record.currency, 'LKR');

  end if;


  -- A driver should know route distance and duration
  -- before bidding.
  if new.status = 'open' then

    if new.route_distance_km is null
       or new.estimated_duration_minutes is null then
      raise exception 'Route distance and estimated duration are required before opening transport request';
    end if;


    if new.bidding_deadline is null
       or new.bidding_deadline <= now() then
      raise exception 'A future bidding deadline is required before opening transport request';
    end if;

  end if;


  return new;
end;
$$;


drop trigger if exists populate_transport_request_snapshot_trigger
on public.transport_requests;

create trigger populate_transport_request_snapshot_trigger
before insert or update
on public.transport_requests
for each row
execute procedure public.populate_transport_request_snapshot();



-- =========================================================
-- 13. TRANSPORT REQUEST ROUTE STOPS
-- =========================================================

create table if not exists public.transport_request_stops (
  id bigint generated by default as identity primary key,

  transport_request_id bigint not null
    references public.transport_requests(id)
    on delete cascade,

  stop_order integer not null
    check (stop_order >= 0),

  stop_type text not null
    check (
      stop_type in (
        'pickup',
        'destination'
      )
    ),

  location_name text not null,

  latitude numeric(9,6),
  longitude numeric(9,6),

  planned_arrival_date date,
  planned_departure_date date,

  created_at timestamptz not null default now(),

  unique (
    transport_request_id,
    stop_order
  )
);


create index if not exists transport_request_stops_request_idx
on public.transport_request_stops(transport_request_id);



-- Automatically create pickup + destination snapshots
create or replace function public.create_transport_request_stops()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin

  -- Pickup
  insert into public.transport_request_stops (
    transport_request_id,
    stop_order,
    stop_type,
    location_name,
    latitude,
    longitude,
    planned_departure_date
  )
  values (
    new.id,
    0,
    'pickup',
    new.pickup_location_snapshot,
    new.pickup_latitude,
    new.pickup_longitude,
    new.trip_start_date
  );


  -- Destinations
  insert into public.transport_request_stops (
    transport_request_id,
    stop_order,
    stop_type,
    location_name,
    latitude,
    longitude,
    planned_arrival_date,
    planned_departure_date
  )
  select
    new.id,
    td.visit_order,
    'destination',
    d.name,
    d.latitude,
    d.longitude,
    td.planned_arrival_date,
    td.planned_departure_date
  from public.trip_destinations td
  join public.destinations d
    on d.id = td.destination_id
  where td.trip_id = new.trip_id
  order by td.visit_order;


  return new;
end;
$$;


drop trigger if exists create_transport_request_stops_trigger
on public.transport_requests;

create trigger create_transport_request_stops_trigger
after insert
on public.transport_requests
for each row
execute procedure public.create_transport_request_stops();



-- =========================================================
-- 14. DRIVER BIDS
-- =========================================================

create table if not exists public.driver_bids (
  id bigint generated by default as identity primary key,

  transport_request_id bigint not null
    references public.transport_requests(id)
    on delete cascade,

  driver_id uuid not null
    references public.driver_profiles(user_id)
    on delete cascade,

  vehicle_id bigint not null
    references public.vehicles(id)
    on delete restrict,

  bid_amount numeric(12,2) not null
    check (bid_amount > 0),

  currency text not null default 'LKR',

  message text,

  status text not null default 'pending'
    check (
      status in (
        'pending',
        'accepted',
        'rejected',
        'withdrawn',
        'expired'
      )
    ),

  expires_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create index if not exists driver_bids_request_idx
on public.driver_bids(transport_request_id);


create index if not exists driver_bids_driver_idx
on public.driver_bids(driver_id);


-- One active bid per driver/request.
-- Driver may withdraw and submit another one later.
create unique index if not exists one_pending_bid_per_driver_request_idx
on public.driver_bids(
  transport_request_id,
  driver_id
)
where status = 'pending';


-- Critical race-condition protection:
-- only one accepted bid per transport request.
create unique index if not exists one_accepted_bid_per_request_idx
on public.driver_bids(transport_request_id)
where status = 'accepted';


drop trigger if exists set_driver_bids_updated_at
on public.driver_bids;

create trigger set_driver_bids_updated_at
before update
on public.driver_bids
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 15. BID VALIDATION
-- =========================================================

create or replace function public.validate_driver_bid()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_record record;
  driver_record record;
  vehicle_record record;
begin

  -- Full validation is required while bid is active/pending
  if new.status <> 'pending' then
    return new;
  end if;


  select
    tr.status,
    tr.bidding_deadline,
    tr.passenger_count,
    tr.luggage_count,
    tr.trip_start_date,
    tr.trip_end_date,
    tr.currency
  into request_record
  from public.transport_requests tr
  where tr.id = new.transport_request_id;


  if not found then
    raise exception 'Transport request does not exist';
  end if;


  if request_record.status <> 'open' then
    raise exception 'Transport request is not open for bidding';
  end if;


  if request_record.bidding_deadline is null
     or request_record.bidding_deadline <= now() then
    raise exception 'Bidding deadline has passed';
  end if;


  -- Driver account must be approved
  if not public.is_provider_approved(
    new.driver_id,
    'driver'
  ) then
    raise exception 'Driver is not approved';
  end if;


  select
    dp.is_accepting_requests,
    dl.expiry_date
  into driver_record
  from public.driver_profiles dp
  left join public.driver_licenses dl
    on dl.driver_id = dp.user_id
  where dp.user_id = new.driver_id;


  if not found then
    raise exception 'Driver profile does not exist';
  end if;


  if driver_record.is_accepting_requests is not true then
    raise exception 'Driver is not accepting trip requests';
  end if;


  if driver_record.expiry_date is null then
    raise exception 'Driver licence information is required';
  end if;


  -- Licence must remain valid for the entire trip
  if driver_record.expiry_date < request_record.trip_end_date then
    raise exception 'Driver licence expires before trip completion';
  end if;


  -- Vehicle must belong to this driver and be approved
  select
    v.passenger_capacity,
    v.luggage_capacity,
    v.is_active,
    vv.status as verification_status
  into vehicle_record
  from public.vehicles v
  left join public.vehicle_verifications vv
    on vv.vehicle_id = v.id
  where v.id = new.vehicle_id
    and v.driver_id = new.driver_id;


  if not found then
    raise exception 'Vehicle does not belong to this driver';
  end if;


  if vehicle_record.is_active is not true then
    raise exception 'Vehicle is inactive';
  end if;


  if vehicle_record.verification_status is distinct from 'approved' then
    raise exception 'Vehicle is not approved';
  end if;


  if vehicle_record.passenger_capacity
     < request_record.passenger_count then
    raise exception 'Vehicle does not have enough passenger capacity';
  end if;


  if vehicle_record.luggage_capacity
     < request_record.luggage_count then
    raise exception 'Vehicle does not have enough luggage capacity';
  end if;


  -- Block bids where driver is marked unavailable/booked
  -- during any date in the requested trip.
  if exists (
    select 1
    from public.driver_availability da
    where da.driver_id = new.driver_id
      and da.availability_date
          between request_record.trip_start_date
          and request_record.trip_end_date
      and da.status in (
        'unavailable',
        'booked'
      )
  ) then
    raise exception 'Driver is unavailable during requested trip dates';
  end if;


  -- Client does not choose bid currency or expiry.
  new.currency :=
    request_record.currency;

  new.expires_at :=
    request_record.bidding_deadline;


  return new;
end;
$$;


drop trigger if exists validate_driver_bid_trigger
on public.driver_bids;

create trigger validate_driver_bid_trigger
before insert or update
on public.driver_bids
for each row
execute procedure public.validate_driver_bid();



-- =========================================================
-- 16. SELECTED BID REFERENCE
-- Added after driver_bids exists to avoid circular FK issue
-- =========================================================

alter table public.transport_requests
add column if not exists selected_bid_id bigint;


do $$
begin

  if not exists (
    select 1
    from pg_constraint
    where conname = 'transport_requests_selected_bid_fk'
  ) then

    alter table public.transport_requests
    add constraint transport_requests_selected_bid_fk
    foreign key (selected_bid_id)
    references public.driver_bids(id)
    on delete set null;

  end if;

end
$$;


create unique index if not exists transport_request_selected_bid_unique_idx
on public.transport_requests(selected_bid_id)
where selected_bid_id is not null;



-- =========================================================
-- 17. PERFORMANCE INDEXES
-- =========================================================

create index if not exists driver_profiles_accepting_idx
on public.driver_profiles(is_accepting_requests);


create index if not exists vehicle_verification_status_idx
on public.vehicle_verifications(status);


create index if not exists driver_documents_driver_idx
on public.driver_documents(driver_id);


create index if not exists vehicle_documents_vehicle_idx
on public.vehicle_documents(vehicle_id);


create index if not exists transport_requests_open_deadline_idx
on public.transport_requests(
  status,
  bidding_deadline
);
