-- =========================================================
-- TripMate
-- Migration 021: Booking / Checkout Core
-- =========================================================


-- =========================================================
-- 1. BOOKINGS
-- One booking belongs to one traveler + one trip.
-- =========================================================

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,

  booking_reference text not null unique
    default (
      'TM-' ||
      upper(
        substr(
          replace(gen_random_uuid()::text, '-', ''),
          1,
          12
        )
      )
    ),

  traveler_id uuid not null
    references public.profiles(id)
    on delete restrict,

  trip_id bigint not null
    references public.trips(id)
    on delete restrict,

  status text not null default 'pending'
    check (
      status in (
        'pending',
        'confirmed',
        'partially_cancelled',
        'cancelled',
        'completed',
        'failed',
        'expired'
      )
    ),

  payment_status text not null default 'unpaid'
    check (
      payment_status in (
        'unpaid',
        'pending',
        'paid',
        'partially_refunded',
        'refunded',
        'failed'
      )
    ),

  currency text not null default 'LKR',

  subtotal numeric(14,2) not null default 0
    check (subtotal >= 0),

  discount_total numeric(14,2) not null default 0
    check (discount_total >= 0),

  service_fee_total numeric(14,2) not null default 0
    check (service_fee_total >= 0),

  tax_total numeric(14,2) not null default 0
    check (tax_total >= 0),

  total_amount numeric(14,2)
    generated always as (
      subtotal
      - discount_total
      + service_fee_total
      + tax_total
    ) stored,

  traveler_notes text,

  confirmed_at timestamptz,
  cancelled_at timestamptz,
  completed_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  check (discount_total <= subtotal)
);


create index if not exists bookings_traveler_idx
on public.bookings(traveler_id);


create index if not exists bookings_trip_idx
on public.bookings(trip_id);


create index if not exists bookings_status_idx
on public.bookings(status);


create index if not exists bookings_reference_idx
on public.bookings(booking_reference);


drop trigger if exists set_bookings_updated_at
on public.bookings;

create trigger set_bookings_updated_at
before update
on public.bookings
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 2. BOOKING ITEMS
--
-- Historical snapshot:
-- booking must remain understandable even if provider later
-- edits or deletes the original service.
-- =========================================================

create table if not exists public.booking_items (
  id bigint generated by default as identity primary key,

  booking_id bigint not null
    references public.bookings(id)
    on delete cascade,

  item_type text not null
    check (
      item_type in (
        'room',
        'food',
        'buffet',
        'restaurant_reservation',
        'attraction',
        'activity',
        'transport'
      )
    ),

  -- -------------------------------------------------------
  -- Original service references.
  -- SET NULL preserves historical booking snapshots if the
  -- original service is later removed.
  -- -------------------------------------------------------

  room_type_id bigint
    references public.room_types(id)
    on delete set null,

  food_item_id bigint
    references public.food_items(id)
    on delete set null,

  buffet_package_id bigint
    references public.buffet_packages(id)
    on delete set null,

  restaurant_id bigint
    references public.restaurants(id)
    on delete set null,

  attraction_id bigint
    references public.attractions(id)
    on delete set null,

  activity_id bigint
    references public.activities(id)
    on delete set null,

  driver_bid_id bigint
    references public.driver_bids(id)
    on delete set null,

  accommodation_meal_plan_id bigint
    references public.accommodation_meal_plans(id)
    on delete set null,

  -- -------------------------------------------------------
  -- Immutable historical snapshots
  -- -------------------------------------------------------

  item_name_snapshot text not null,

  provider_name_snapshot text,

  description_snapshot text,

  currency text not null default 'LKR',

  quantity integer not null default 1
    check (quantity > 0),

  -- Number of price units:
  -- food x 2       -> 2
  -- room 2 rooms x 3 nights -> 6
  -- buffet 4 persons -> 4
  -- transport -> 1
  billing_units numeric(12,2) not null default 1
    check (billing_units > 0),

  unit_price_snapshot numeric(14,2) not null
    check (unit_price_snapshot >= 0),

  discount_total numeric(14,2) not null default 0
    check (discount_total >= 0),

  tax_total numeric(14,2) not null default 0
    check (tax_total >= 0),

  line_subtotal numeric(14,2)
    generated always as (
      unit_price_snapshot * billing_units
    ) stored,

  line_total numeric(14,2)
    generated always as (
      (unit_price_snapshot * billing_units)
      - discount_total
      + tax_total
    ) stored,

  -- -------------------------------------------------------
  -- Service date/time snapshot
  -- -------------------------------------------------------

  service_date date,
  service_start_time time,
  service_end_time time,

  check_in_date date,
  check_out_date date,

  -- Party/participant snapshot
  adult_count integer
    check (
      adult_count is null
      or adult_count >= 0
    ),

  child_count integer
    check (
      child_count is null
      or child_count >= 0
    ),

  notes text,

  -- Flexible snapshot for service-specific details:
  -- selected meal plan, room facilities, route,
  -- offer information, etc.
  snapshot_data jsonb not null default '{}'::jsonb,

  status text not null default 'pending'
    check (
      status in (
        'pending',
        'confirmed',
        'cancelled',
        'completed',
        'failed'
      )
    ),

  created_at timestamptz not null default now(),

  check (
    discount_total
    <= (unit_price_snapshot * billing_units)
  ),

  check (
    check_out_date is null
    or check_in_date is not null
  ),

  check (
    check_in_date is null
    or check_out_date is null
    or check_out_date > check_in_date
  )
);


create index if not exists booking_items_booking_idx
on public.booking_items(booking_id);


create index if not exists booking_items_type_idx
on public.booking_items(item_type);


create index if not exists booking_items_room_idx
on public.booking_items(room_type_id)
where room_type_id is not null;


create index if not exists booking_items_activity_idx
on public.booking_items(activity_id)
where activity_id is not null;


create index if not exists booking_items_driver_bid_idx
on public.booking_items(driver_bid_id)
where driver_bid_id is not null;



-- =========================================================
-- 3. VALIDATE BOOKING ITEM SOURCE ON INSERT
--
-- Exactly the correct source must exist when booking is
-- created.
--
-- This runs on INSERT only so historical records remain
-- valid even if original service records are later deleted.
-- =========================================================

create or replace function public.validate_booking_item_source()
returns trigger
language plpgsql
set search_path = ''
as $$
begin

  if new.item_type = 'room' then

    if new.room_type_id is null
       or new.food_item_id is not null
       or new.buffet_package_id is not null
       or new.restaurant_id is not null
       or new.attraction_id is not null
       or new.activity_id is not null
       or new.driver_bid_id is not null then

      raise exception
        'Room booking item has invalid source references';

    end if;


  elsif new.item_type = 'food' then

    if new.food_item_id is null
       or new.room_type_id is not null
       or new.buffet_package_id is not null
       or new.restaurant_id is not null
       or new.attraction_id is not null
       or new.activity_id is not null
       or new.driver_bid_id is not null then

      raise exception
        'Food booking item has invalid source references';

    end if;


  elsif new.item_type = 'buffet' then

    if new.buffet_package_id is null
       or new.room_type_id is not null
       or new.food_item_id is not null
       or new.restaurant_id is not null
       or new.attraction_id is not null
       or new.activity_id is not null
       or new.driver_bid_id is not null then

      raise exception
        'Buffet booking item has invalid source references';

    end if;


  elsif new.item_type = 'restaurant_reservation' then

    if new.restaurant_id is null
       or new.room_type_id is not null
       or new.food_item_id is not null
       or new.buffet_package_id is not null
       or new.attraction_id is not null
       or new.activity_id is not null
       or new.driver_bid_id is not null then

      raise exception
        'Restaurant reservation has invalid source references';

    end if;


  elsif new.item_type = 'attraction' then

    if new.attraction_id is null
       or new.room_type_id is not null
       or new.food_item_id is not null
       or new.buffet_package_id is not null
       or new.restaurant_id is not null
       or new.activity_id is not null
       or new.driver_bid_id is not null then

      raise exception
        'Attraction booking item has invalid source references';

    end if;


  elsif new.item_type = 'activity' then

    if new.activity_id is null
       or new.room_type_id is not null
       or new.food_item_id is not null
       or new.buffet_package_id is not null
       or new.restaurant_id is not null
       or new.attraction_id is not null
       or new.driver_bid_id is not null then

      raise exception
        'Activity booking item has invalid source references';

    end if;


  elsif new.item_type = 'transport' then

    if new.driver_bid_id is null
       or new.room_type_id is not null
       or new.food_item_id is not null
       or new.buffet_package_id is not null
       or new.restaurant_id is not null
       or new.attraction_id is not null
       or new.activity_id is not null then

      raise exception
        'Transport booking item has invalid source references';

    end if;

  end if;


  return new;
end;
$$;


drop trigger if exists validate_booking_item_source_trigger
on public.booking_items;

create trigger validate_booking_item_source_trigger
before insert
on public.booking_items
for each row
execute procedure public.validate_booking_item_source();



-- =========================================================
-- 4. ROOM INVENTORY RESERVATION LEDGER
--
-- One booking item may reserve several nights.
-- Example:
-- 2 rooms x 3 nights = 3 reservation rows,
-- each row reserving 2 rooms.
-- =========================================================

create table if not exists public.room_inventory_reservations (
  id bigint generated by default as identity primary key,

  booking_item_id bigint not null
    references public.booking_items(id)
    on delete cascade,

  room_type_id bigint
    references public.room_types(id)
    on delete set null,

  stay_date date not null,

  rooms_reserved integer not null
    check (rooms_reserved > 0),

  price_per_room_snapshot numeric(14,2) not null
    check (price_per_room_snapshot >= 0),

  status text not null default 'reserved'
    check (
      status in (
        'reserved',
        'released'
      )
    ),

  released_at timestamptz,

  created_at timestamptz not null default now(),

  unique (
    booking_item_id,
    stay_date
  )
);


create index if not exists
room_inventory_reservations_room_date_idx
on public.room_inventory_reservations(
  room_type_id,
  stay_date
);


create index if not exists
room_inventory_reservations_active_idx
on public.room_inventory_reservations(
  room_type_id,
  stay_date
)
where status = 'reserved';



-- =========================================================
-- 5. ACTIVITY INVENTORY RESERVATION LEDGER
--
-- Stores exactly which activity slot was consumed.
-- =========================================================

create table if not exists public.activity_inventory_reservations (
  id bigint generated by default as identity primary key,

  booking_item_id bigint not null unique
    references public.booking_items(id)
    on delete cascade,

  activity_availability_id bigint
    references public.activity_availability(id)
    on delete set null,

  participants_reserved integer not null
    check (participants_reserved > 0),

  price_per_person_snapshot numeric(14,2) not null
    check (price_per_person_snapshot >= 0),

  status text not null default 'reserved'
    check (
      status in (
        'reserved',
        'released'
      )
    ),

  released_at timestamptz,

  created_at timestamptz not null default now()
);


create index if not exists
activity_inventory_reservations_slot_idx
on public.activity_inventory_reservations(
  activity_availability_id
)
where status = 'reserved';



-- =========================================================
-- 6. BOOKING STATUS HISTORY
-- Audit trail for viva + real system traceability.
-- =========================================================

create table if not exists public.booking_status_history (
  id bigint generated by default as identity primary key,

  booking_id bigint not null
    references public.bookings(id)
    on delete cascade,

  old_status text,

  new_status text not null,

  changed_by uuid
    references public.profiles(id)
    on delete set null,

  reason text,

  created_at timestamptz not null default now()
);


create index if not exists booking_status_history_booking_idx
on public.booking_status_history(
  booking_id,
  created_at
);



-- =========================================================
-- 7. AUTOMATIC BOOKING STATUS AUDIT
-- =========================================================

create or replace function public.log_booking_status_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin

  if tg_op = 'INSERT' then

    insert into public.booking_status_history (
      booking_id,
      old_status,
      new_status,
      changed_by
    )
    values (
      new.id,
      null,
      new.status,
      auth.uid()
    );


  elsif new.status is distinct from old.status then

    insert into public.booking_status_history (
      booking_id,
      old_status,
      new_status,
      changed_by
    )
    values (
      new.id,
      old.status,
      new.status,
      auth.uid()
    );

  end if;


  return new;
end;
$$;


drop trigger if exists log_booking_status_change_trigger
on public.bookings;

create trigger log_booking_status_change_trigger
after insert or update of status
on public.bookings
for each row
execute procedure public.log_booking_status_change();



-- =========================================================
-- 8. CANCELLATION FOUNDATION
--
-- Can represent:
--   full booking cancellation
--   single booking-item cancellation
--
-- Refund processing will be handled separately later.
-- =========================================================

create table if not exists public.booking_cancellations (
  id bigint generated by default as identity primary key,

  booking_id bigint not null
    references public.bookings(id)
    on delete cascade,

  booking_item_id bigint
    references public.booking_items(id)
    on delete cascade,

  requested_by uuid not null
    references public.profiles(id)
    on delete restrict,

  cancellation_type text not null
    check (
      cancellation_type in (
        'full_booking',
        'booking_item'
      )
    ),

  reason text,

  status text not null default 'requested'
    check (
      status in (
        'requested',
        'approved',
        'rejected',
        'processed'
      )
    ),

  refund_amount numeric(14,2)
    check (
      refund_amount is null
      or refund_amount >= 0
    ),

  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  processed_at timestamptz,

  check (
    (
      cancellation_type = 'full_booking'
      and booking_item_id is null
    )
    or
    (
      cancellation_type = 'booking_item'
      and booking_item_id is not null
    )
  )
);


create index if not exists booking_cancellations_booking_idx
on public.booking_cancellations(booking_id);


create index if not exists booking_cancellations_item_idx
on public.booking_cancellations(booking_item_id)
where booking_item_id is not null;



-- =========================================================
-- 9. BASIC DATA-INTEGRITY TRIGGER
--
-- Prevent cancellation request from referencing an item
-- that belongs to another booking.
-- =========================================================

create or replace function public.validate_booking_cancellation_item()
returns trigger
language plpgsql
set search_path = ''
as $$
begin

  if new.booking_item_id is not null then

    if not exists (
      select 1
      from public.booking_items bi
      where bi.id = new.booking_item_id
        and bi.booking_id = new.booking_id
    ) then

      raise exception
        'Booking item does not belong to this booking';

    end if;

  end if;


  return new;
end;
$$;


drop trigger if exists
validate_booking_cancellation_item_trigger
on public.booking_cancellations;

create trigger
validate_booking_cancellation_item_trigger
before insert or update
on public.booking_cancellations
for each row
execute procedure
public.validate_booking_cancellation_item();



-- =========================================================
-- 10. PERFORMANCE INDEXES
-- =========================================================

create index if not exists booking_items_service_date_idx
on public.booking_items(service_date);


create index if not exists booking_items_checkin_idx
on public.booking_items(check_in_date)
where check_in_date is not null;


create index if not exists booking_items_status_idx
on public.booking_items(status);
