-- =========================================================
-- TripMate
-- Migration 026: Reviews + Notifications Core
-- =========================================================


-- =========================================================
-- 1. REVIEWS
--
-- One genuine review is linked to one real booking item.
-- A secure workflow will later decide whether that booking
-- item is actually eligible for review.
-- =========================================================

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,

  booking_item_id bigint not null unique
    references public.booking_items(id)
    on delete restrict,

  booking_id bigint not null
    references public.bookings(id)
    on delete restrict,

  reviewer_id uuid not null
    references public.profiles(id)
    on delete restrict,

  -- -------------------------------------------------------
  -- Review target
  --
  -- room      -> accommodation
  -- food      -> restaurant
  -- buffet    -> restaurant
  -- reservation -> restaurant
  -- attraction -> attraction
  -- activity   -> activity
  -- transport  -> driver
  -- -------------------------------------------------------

  target_type text not null
    check (
      target_type in (
        'accommodation',
        'restaurant',
        'attraction',
        'activity',
        'driver'
      )
    ),

  accommodation_id bigint
    references public.accommodations(id)
    on delete set null,

  restaurant_id bigint
    references public.restaurants(id)
    on delete set null,

  attraction_id bigint
    references public.attractions(id)
    on delete set null,

  activity_id bigint
    references public.activities(id)
    on delete set null,

  driver_id uuid
    references public.driver_profiles(user_id)
    on delete set null,

  target_provider_user_id uuid
    references public.profiles(id)
    on delete set null,

  -- -------------------------------------------------------
  -- Rating + content
  -- -------------------------------------------------------

  rating integer not null
    check (rating between 1 and 5),

  title text,

  comment text,

  -- -------------------------------------------------------
  -- Moderation state
  -- -------------------------------------------------------

  status text not null default 'pending'
    check (
      status in (
        'pending',
        'published',
        'hidden',
        'rejected'
      )
    ),

  moderation_notes text,

  -- -------------------------------------------------------
  -- Provider reply
  -- One provider reply per review for current project scope
  -- -------------------------------------------------------

  provider_reply text,

  provider_replied_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create index if not exists reviews_reviewer_idx
on public.reviews(reviewer_id);


create index if not exists reviews_booking_idx
on public.reviews(booking_id);


create index if not exists reviews_target_type_idx
on public.reviews(target_type);


create index if not exists reviews_accommodation_idx
on public.reviews(accommodation_id)
where accommodation_id is not null;


create index if not exists reviews_restaurant_idx
on public.reviews(restaurant_id)
where restaurant_id is not null;


create index if not exists reviews_attraction_idx
on public.reviews(attraction_id)
where attraction_id is not null;


create index if not exists reviews_activity_idx
on public.reviews(activity_id)
where activity_id is not null;


create index if not exists reviews_driver_idx
on public.reviews(driver_id)
where driver_id is not null;


create index if not exists reviews_published_idx
on public.reviews(status, created_at)
where status = 'published';


drop trigger if exists set_reviews_updated_at
on public.reviews;

create trigger set_reviews_updated_at
before update
on public.reviews
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 2. REVIEW TARGET SNAPSHOT / INTEGRITY
--
-- Never trust target IDs sent from frontend.
-- Booking item determines the real review target.
-- =========================================================

create or replace function public.populate_review_target()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item public.booking_items%rowtype;
begin

  select *
  into v_item
  from public.booking_items
  where id = new.booking_item_id;


  if not found then
    raise exception 'Booking item does not exist';
  end if;


  -- Always copy authoritative booking ownership
  new.booking_id := v_item.booking_id;

  -- Reset all possible targets first
  new.accommodation_id := null;
  new.restaurant_id := null;
  new.attraction_id := null;
  new.activity_id := null;
  new.driver_id := null;
  new.target_provider_user_id :=
    v_item.provider_user_id_snapshot;


  -- -------------------------------------------------------
  -- ROOM -> ACCOMMODATION
  -- -------------------------------------------------------

  if v_item.item_type = 'room' then

    new.target_type := 'accommodation';

    select rt.accommodation_id
    into new.accommodation_id
    from public.room_types rt
    where rt.id = v_item.room_type_id;


    if new.accommodation_id is null then
      raise exception
        'Accommodation review target is unavailable';
    end if;


  -- -------------------------------------------------------
  -- FOOD / BUFFET / RESTAURANT RESERVATION -> RESTAURANT
  -- -------------------------------------------------------

  elsif v_item.item_type = 'food' then

    new.target_type := 'restaurant';

    select fi.restaurant_id
    into new.restaurant_id
    from public.food_items fi
    where fi.id = v_item.food_item_id;


    if new.restaurant_id is null then
      raise exception
        'Restaurant review target is unavailable';
    end if;


  elsif v_item.item_type = 'buffet' then

    new.target_type := 'restaurant';

    select bp.restaurant_id
    into new.restaurant_id
    from public.buffet_packages bp
    where bp.id = v_item.buffet_package_id;


    if new.restaurant_id is null then
      raise exception
        'Restaurant review target is unavailable';
    end if;


  elsif v_item.item_type = 'restaurant_reservation' then

    new.target_type := 'restaurant';
    new.restaurant_id := v_item.restaurant_id;


    if new.restaurant_id is null then
      raise exception
        'Restaurant review target is unavailable';
    end if;


  -- -------------------------------------------------------
  -- ATTRACTION
  -- -------------------------------------------------------

  elsif v_item.item_type = 'attraction' then

    new.target_type := 'attraction';
    new.attraction_id := v_item.attraction_id;


    if new.attraction_id is null then
      raise exception
        'Attraction review target is unavailable';
    end if;


  -- -------------------------------------------------------
  -- ACTIVITY
  -- -------------------------------------------------------

  elsif v_item.item_type = 'activity' then

    new.target_type := 'activity';
    new.activity_id := v_item.activity_id;


    if new.activity_id is null then
      raise exception
        'Activity review target is unavailable';
    end if;


  -- -------------------------------------------------------
  -- TRANSPORT -> DRIVER
  -- -------------------------------------------------------

  elsif v_item.item_type = 'transport' then

    new.target_type := 'driver';

    select db.driver_id
    into new.driver_id
    from public.driver_bids db
    where db.id = v_item.driver_bid_id;


    if new.driver_id is null then
      raise exception
        'Driver review target is unavailable';
    end if;


  else

    raise exception
      'Booking item type is not reviewable';

  end if;


  return new;

end;
$$;


drop trigger if exists populate_review_target_trigger
on public.reviews;

create trigger populate_review_target_trigger
before insert
on public.reviews
for each row
execute procedure public.populate_review_target();



-- =========================================================
-- 3. NOTIFICATIONS
--
-- event_key provides idempotency:
-- same event should not generate duplicate notifications.
-- =========================================================

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references public.profiles(id)
    on delete cascade,

  notification_type text not null
    check (
      notification_type in (
        'booking_confirmed',
        'booking_cancelled',
        'cancellation_requested',
        'cancellation_approved',
        'cancellation_rejected',

        'driver_bid_received',
        'driver_bid_accepted',
        'driver_bid_rejected',

        'provider_verification_approved',
        'provider_verification_rejected',
        'provider_verification_suspended',

        'vehicle_verification_approved',
        'vehicle_verification_rejected',
        'vehicle_verification_suspended',

        'review_received',
        'review_reply',

        'trip_reminder',
        'service_reminder',

        'system'
      )
    ),

  title text not null,

  message text not null,

  -- Stable unique key for event deduplication.
  -- Example:
  -- booking-confirmed:123
  -- bid-received:456
  event_key text unique,

  -- Generic related entity reference.
  -- IDs may be bigint or UUID, so stored as text.
  related_entity_type text,

  related_entity_id text,

  -- Frontend navigation destination
  deep_link text,

  -- Additional structured context
  data jsonb not null default '{}'::jsonb,

  priority text not null default 'normal'
    check (
      priority in (
        'low',
        'normal',
        'high'
      )
    ),

  is_read boolean not null default false,

  read_at timestamptz,

  scheduled_for timestamptz,

  sent_at timestamptz,

  expires_at timestamptz,

  created_at timestamptz not null default now(),

  check (
    (
      is_read = false
      and read_at is null
    )
    or
    (
      is_read = true
      and read_at is not null
    )
  )
);


create index if not exists notifications_user_idx
on public.notifications(
  user_id,
  created_at desc
);


create index if not exists notifications_unread_idx
on public.notifications(
  user_id,
  created_at desc
)
where is_read = false;


create index if not exists notifications_scheduled_idx
on public.notifications(scheduled_for)
where scheduled_for is not null
  and sent_at is null;



-- =========================================================
-- 4. NOTIFICATION READ-STATE INTEGRITY
--
-- If client marks notification read:
-- read_at is populated automatically.
--
-- If unread:
-- read_at is cleared.
-- =========================================================

create or replace function public.sync_notification_read_state()
returns trigger
language plpgsql
set search_path = ''
as $$
begin

  if new.is_read is true then

    if new.read_at is null then
      new.read_at := now();
    end if;

  else

    new.read_at := null;

  end if;


  return new;

end;
$$;


drop trigger if exists sync_notification_read_state_trigger
on public.notifications;

create trigger sync_notification_read_state_trigger
before insert or update of is_read
on public.notifications
for each row
execute procedure public.sync_notification_read_state();



-- =========================================================
-- 5. NOTIFICATION PREFERENCES
--
-- In-app notifications stay enabled by default.
-- Email / push integrations can be connected later.
-- =========================================================

create table if not exists public.notification_preferences (
  user_id uuid primary key
    references public.profiles(id)
    on delete cascade,

  in_app_enabled boolean not null default true,

  email_enabled boolean not null default false,

  push_enabled boolean not null default false,

  booking_updates boolean not null default true,

  driver_bid_updates boolean not null default true,

  verification_updates boolean not null default true,

  review_updates boolean not null default true,

  trip_reminders boolean not null default true,

  service_reminders boolean not null default true,

  updated_at timestamptz not null default now()
);


drop trigger if exists
set_notification_preferences_updated_at
on public.notification_preferences;

create trigger
set_notification_preferences_updated_at
before update
on public.notification_preferences
for each row
execute procedure public.set_updated_at();



-- =========================================================
-- 6. AUTO-CREATE NOTIFICATION PREFERENCES
-- FOR NEW PROFILE ROWS
-- =========================================================

create or replace function
public.create_default_notification_preferences()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin

  insert into public.notification_preferences (
    user_id
  )
  values (
    new.id
  )
  on conflict (user_id) do nothing;


  return new;

end;
$$;


drop trigger if exists
create_default_notification_preferences_trigger
on public.profiles;

create trigger
create_default_notification_preferences_trigger
after insert
on public.profiles
for each row
execute procedure
public.create_default_notification_preferences();



-- =========================================================
-- 7. BACKFILL EXISTING USERS
-- =========================================================

insert into public.notification_preferences (
  user_id
)
select p.id
from public.profiles p
on conflict (user_id) do nothing;



-- =========================================================
-- 8. PERFORMANCE INDEX
-- =========================================================

create index if not exists
notification_preferences_reminders_idx
on public.notification_preferences(
  trip_reminders,
  service_reminders
);
