-- =========================================================
-- TripMate
-- Migration 029: Admin Verification Workflows
-- =========================================================


-- =========================================================
-- 1. ADD REVIEW INFORMATION
-- =========================================================

alter table public.provider_verifications
add column if not exists review_notes text;


alter table public.driver_documents
add column if not exists reviewed_by uuid
references public.profiles(id)
on delete set null;

alter table public.driver_documents
add column if not exists reviewed_at timestamptz;


alter table public.vehicle_documents
add column if not exists reviewed_by uuid
references public.profiles(id)
on delete set null;

alter table public.vehicle_documents
add column if not exists reviewed_at timestamptz;



-- =========================================================
-- 2. ADMIN VERIFICATION AUDIT LOG
--
-- Keeps historical evidence of every verification decision.
-- =========================================================

create table if not exists public.verification_audit_log (
  id bigint generated by default as identity primary key,

  admin_id uuid not null
    references public.profiles(id)
    on delete restrict,

  target_user_id uuid
    references public.profiles(id)
    on delete set null,

  entity_type text not null
    check (
      entity_type in (
        'provider_verification',
        'vehicle_verification',
        'driver_document',
        'vehicle_document'
      )
    ),

  entity_id text not null,

  old_status text,
  new_status text not null,

  notes text,

  created_at timestamptz not null default now()
);


create index if not exists
verification_audit_admin_idx
on public.verification_audit_log(
  admin_id,
  created_at desc
);


create index if not exists
verification_audit_entity_idx
on public.verification_audit_log(
  entity_type,
  entity_id,
  created_at desc
);



-- =========================================================
-- 3. ADMIN VISIBILITY
--
-- Admin dashboard must see pending providers, businesses,
-- documents and vehicles even before public approval.
-- =========================================================

drop policy if exists
"Admins view profiles"
on public.profiles;

create policy
"Admins view profiles"
on public.profiles
for select
to authenticated
using (
  public.is_admin_user()
);


drop policy if exists
"Admins view provider verifications"
on public.provider_verifications;

create policy
"Admins view provider verifications"
on public.provider_verifications
for select
to authenticated
using (
  public.is_admin_user()
);


drop policy if exists
"Admins view restaurants"
on public.restaurants;

create policy
"Admins view restaurants"
on public.restaurants
for select
to authenticated
using (
  public.is_admin_user()
);


drop policy if exists
"Admins view accommodations"
on public.accommodations;

create policy
"Admins view accommodations"
on public.accommodations
for select
to authenticated
using (
  public.is_admin_user()
);


drop policy if exists
"Admins view driver profiles"
on public.driver_profiles;

create policy
"Admins view driver profiles"
on public.driver_profiles
for select
to authenticated
using (
  public.is_admin_user()
);


drop policy if exists
"Admins view driver licences"
on public.driver_licenses;

create policy
"Admins view driver licences"
on public.driver_licenses
for select
to authenticated
using (
  public.is_admin_user()
);


drop policy if exists
"Admins view driver documents"
on public.driver_documents;

create policy
"Admins view driver documents"
on public.driver_documents
for select
to authenticated
using (
  public.is_admin_user()
);


drop policy if exists
"Admins view vehicles"
on public.vehicles;

create policy
"Admins view vehicles"
on public.vehicles
for select
to authenticated
using (
  public.is_admin_user()
);


drop policy if exists
"Admins view vehicle verifications"
on public.vehicle_verifications;

create policy
"Admins view vehicle verifications"
on public.vehicle_verifications
for select
to authenticated
using (
  public.is_admin_user()
);


drop policy if exists
"Admins view vehicle documents"
on public.vehicle_documents;

create policy
"Admins view vehicle documents"
on public.vehicle_documents
for select
to authenticated
using (
  public.is_admin_user()
);



-- =========================================================
-- 4. AUDIT LOG SECURITY
-- =========================================================

alter table public.verification_audit_log
enable row level security;


drop policy if exists
"Admins view verification audit"
on public.verification_audit_log;

create policy
"Admins view verification audit"
on public.verification_audit_log
for select
to authenticated
using (
  public.is_admin_user()
);



-- =========================================================
-- 5. REVIEW PROVIDER VERIFICATION
--
-- Supports:
--   restaurant
--   accommodation
--   driver
--
-- Admin only.
-- =========================================================

create or replace function public.review_provider_verification(
  p_user_id uuid,
  p_provider_type text,
  p_decision text,
  p_notes text default null
)
returns public.provider_verifications
language plpgsql
security definer
set search_path = ''
as $$
declare

  v_verification public.provider_verifications%rowtype;

  v_profile_role text;

  v_expected_role text;

  v_license_expiry date;

  v_result public.provider_verifications%rowtype;

begin

  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;


  if not public.is_admin_user() then
    raise exception
      'Only an administrator can review provider verification';
  end if;


  if p_decision not in (
    'approved',
    'rejected',
    'suspended'
  ) then

    raise exception
      'Decision must be approved, rejected or suspended';

  end if;


  if p_provider_type = 'restaurant' then

    v_expected_role := 'restaurant_owner';

  elsif p_provider_type = 'accommodation' then

    v_expected_role := 'accommodation_owner';

  elsif p_provider_type = 'driver' then

    v_expected_role := 'driver';

  else

    raise exception
      'Invalid provider type';

  end if;



  -- -------------------------------------------------------
  -- Validate account role
  -- -------------------------------------------------------

  select p.role
  into v_profile_role
  from public.profiles p
  where p.id = p_user_id;


  if not found then
    raise exception 'Provider profile does not exist';
  end if;


  if v_profile_role <> v_expected_role then

    raise exception
      'Profile role does not match provider type';

  end if;



  -- -------------------------------------------------------
  -- Lock verification request
  -- -------------------------------------------------------

  select *
  into v_verification

  from public.provider_verifications pv

  where pv.user_id = p_user_id
    and pv.provider_type = p_provider_type

  for update;


  if not found then

    raise exception
      'Provider verification request does not exist';

  end if;



  -- =======================================================
  -- EXTRA DRIVER APPROVAL REQUIREMENTS
  -- =======================================================

  if p_provider_type = 'driver'
     and p_decision = 'approved' then


    -- Driver profile must exist
    if not exists (
      select 1
      from public.driver_profiles dp
      where dp.user_id = p_user_id
    ) then

      raise exception
        'Driver profile is required before approval';

    end if;


    -- Valid driving licence record required
    select dl.expiry_date
    into v_license_expiry

    from public.driver_licenses dl

    where dl.driver_id = p_user_id;


    if not found then

      raise exception
        'Driver licence information is required before approval';

    end if;


    if v_license_expiry < current_date then

      raise exception
        'Expired driver licence cannot be approved';

    end if;


    -- At least one approved identity document
    if not exists (
      select 1
      from public.driver_documents dd

      where dd.driver_id = p_user_id

        and dd.document_type in (
          'nic',
          'passport'
        )

        and dd.verification_status = 'approved'

        and (
          dd.expiry_date is null
          or dd.expiry_date >= current_date
        )
    ) then

      raise exception
        'An approved identity document is required before driver approval';

    end if;

  end if;



  -- -------------------------------------------------------
  -- Update provider verification
  -- Automatic notification trigger from migration 028
  -- will notify provider when status changes.
  -- -------------------------------------------------------

  update public.provider_verifications
  set
    status = p_decision,

    reviewed_by = auth.uid(),

    reviewed_at = now(),

    review_notes =
      nullif(trim(p_notes), '')

  where user_id = p_user_id
    and provider_type = p_provider_type

  returning *
  into v_result;



  -- -------------------------------------------------------
  -- Audit
  -- -------------------------------------------------------

  insert into public.verification_audit_log (
    admin_id,
    target_user_id,

    entity_type,
    entity_id,

    old_status,
    new_status,

    notes
  )
  values (
    auth.uid(),
    p_user_id,

    'provider_verification',

    p_user_id::text
      || ':'
      || p_provider_type,

    v_verification.status,
    p_decision,

    nullif(trim(p_notes), '')
  );


  return v_result;

end;
$$;



-- =========================================================
-- 6. REVIEW DRIVER DOCUMENT
-- =========================================================

create or replace function public.review_driver_document(
  p_document_id bigint,
  p_decision text,
  p_notes text default null
)
returns public.driver_documents
language plpgsql
security definer
set search_path = ''
as $$
declare

  v_document public.driver_documents%rowtype;

  v_result public.driver_documents%rowtype;

begin

  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;


  if not public.is_admin_user() then
    raise exception
      'Only an administrator can review driver documents';
  end if;


  if p_decision not in (
    'approved',
    'rejected'
  ) then

    raise exception
      'Document decision must be approved or rejected';

  end if;



  select *
  into v_document

  from public.driver_documents

  where id = p_document_id

  for update;


  if not found then
    raise exception 'Driver document does not exist';
  end if;



  -- Cannot approve an already expired document
  if p_decision = 'approved'
     and v_document.expiry_date is not null
     and v_document.expiry_date < current_date then

    raise exception
      'Expired driver document cannot be approved';

  end if;



  update public.driver_documents
  set
    verification_status = p_decision,

    review_notes =
      nullif(trim(p_notes), ''),

    reviewed_by = auth.uid(),

    reviewed_at = now()

  where id = p_document_id

  returning *
  into v_result;



  insert into public.verification_audit_log (
    admin_id,
    target_user_id,

    entity_type,
    entity_id,

    old_status,
    new_status,

    notes
  )
  values (
    auth.uid(),
    v_document.driver_id,

    'driver_document',
    p_document_id::text,

    v_document.verification_status,
    p_decision,

    nullif(trim(p_notes), '')
  );


  return v_result;

end;
$$;



-- =========================================================
-- 7. REVIEW VEHICLE DOCUMENT
-- =========================================================

create or replace function public.review_vehicle_document(
  p_document_id bigint,
  p_decision text,
  p_notes text default null
)
returns public.vehicle_documents
language plpgsql
security definer
set search_path = ''
as $$
declare

  v_document public.vehicle_documents%rowtype;

  v_driver_id uuid;

  v_result public.vehicle_documents%rowtype;

begin

  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;


  if not public.is_admin_user() then
    raise exception
      'Only an administrator can review vehicle documents';
  end if;


  if p_decision not in (
    'approved',
    'rejected'
  ) then

    raise exception
      'Document decision must be approved or rejected';

  end if;



  select *
  into v_document

  from public.vehicle_documents

  where id = p_document_id

  for update;


  if not found then
    raise exception 'Vehicle document does not exist';
  end if;



  select v.driver_id
  into v_driver_id

  from public.vehicles v

  where v.id = v_document.vehicle_id;


  if v_driver_id is null then
    raise exception 'Vehicle owner does not exist';
  end if;



  -- -------------------------------------------------------
  -- Required expiry checks
  -- -------------------------------------------------------

  if p_decision = 'approved' then

    if v_document.document_type in (
      'insurance',
      'revenue_license'
    )
    and (
      v_document.expiry_date is null
      or v_document.expiry_date < current_date
    ) then

      raise exception
        'Insurance and revenue licence require a valid expiry date';

    end if;


    if v_document.expiry_date is not null
       and v_document.expiry_date < current_date then

      raise exception
        'Expired vehicle document cannot be approved';

    end if;

  end if;



  update public.vehicle_documents
  set
    verification_status = p_decision,

    review_notes =
      nullif(trim(p_notes), ''),

    reviewed_by = auth.uid(),

    reviewed_at = now()

  where id = p_document_id

  returning *
  into v_result;



  insert into public.verification_audit_log (
    admin_id,
    target_user_id,

    entity_type,
    entity_id,

    old_status,
    new_status,

    notes
  )
  values (
    auth.uid(),
    v_driver_id,

    'vehicle_document',
    p_document_id::text,

    v_document.verification_status,
    p_decision,

    nullif(trim(p_notes), '')
  );


  return v_result;

end;
$$;



-- =========================================================
-- 8. REVIEW VEHICLE VERIFICATION
--
-- Vehicle can be approved only when:
--   registration approved
--   insurance approved + valid
--   revenue licence approved + valid
-- =========================================================

create or replace function public.review_vehicle_verification(
  p_vehicle_id bigint,
  p_decision text,
  p_notes text default null
)
returns public.vehicle_verifications
language plpgsql
security definer
set search_path = ''
as $$
declare

  v_verification public.vehicle_verifications%rowtype;

  v_driver_id uuid;

  v_vehicle_active boolean;

  v_result public.vehicle_verifications%rowtype;

begin

  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;


  if not public.is_admin_user() then
    raise exception
      'Only an administrator can review vehicle verification';
  end if;


  if p_decision not in (
    'approved',
    'rejected',
    'suspended'
  ) then

    raise exception
      'Decision must be approved, rejected or suspended';

  end if;



  select
    v.driver_id,
    v.is_active

  into
    v_driver_id,
    v_vehicle_active

  from public.vehicles v

  where v.id = p_vehicle_id;


  if not found then
    raise exception 'Vehicle does not exist';
  end if;



  select *
  into v_verification

  from public.vehicle_verifications vv

  where vv.vehicle_id = p_vehicle_id

  for update;


  if not found then
    raise exception
      'Vehicle verification record does not exist';
  end if;



  if p_decision = 'approved' then

    if v_vehicle_active is not true then

      raise exception
        'Inactive vehicle cannot be approved';

    end if;


    -- Uses helper created in migration 018
    if not public.vehicle_is_compliant_for_trip(
      p_vehicle_id,
      current_date
    ) then

      raise exception
        'Vehicle registration, insurance and revenue licence must be approved and currently valid';

    end if;

  end if;



  update public.vehicle_verifications
  set
    status = p_decision,

    reviewed_by = auth.uid(),

    reviewed_at = now(),

    review_notes =
      nullif(trim(p_notes), '')

  where vehicle_id = p_vehicle_id

  returning *
  into v_result;



  insert into public.verification_audit_log (
    admin_id,
    target_user_id,

    entity_type,
    entity_id,

    old_status,
    new_status,

    notes
  )
  values (
    auth.uid(),
    v_driver_id,

    'vehicle_verification',
    p_vehicle_id::text,

    v_verification.status,
    p_decision,

    nullif(trim(p_notes), '')
  );


  return v_result;

end;
$$;



-- =========================================================
-- 9. API PRIVILEGES
-- =========================================================

grant select
on table public.profiles
to authenticated;


grant select
on table public.verification_audit_log
to authenticated;



-- =========================================================
-- 10. SECURE FUNCTION PRIVILEGES
-- =========================================================

revoke all
on function public.review_provider_verification(
  uuid,
  text,
  text,
  text
)
from public, anon;


grant execute
on function public.review_provider_verification(
  uuid,
  text,
  text,
  text
)
to authenticated;



revoke all
on function public.review_driver_document(
  bigint,
  text,
  text
)
from public, anon;


grant execute
on function public.review_driver_document(
  bigint,
  text,
  text
)
to authenticated;



revoke all
on function public.review_vehicle_document(
  bigint,
  text,
  text
)
from public, anon;


grant execute
on function public.review_vehicle_document(
  bigint,
  text,
  text
)
to authenticated;



revoke all
on function public.review_vehicle_verification(
  bigint,
  text,
  text
)
from public, anon;


grant execute
on function public.review_vehicle_verification(
  bigint,
  text,
  text
)
to authenticated;
