-- =========================================================
-- TripMate
-- Migration 035: Secure Payment Foundation
-- =========================================================
--
-- Supports:
--   pay_later
--   cash
--   bank_transfer
--   online_card
--
-- Browser users CANNOT mark bookings as paid.
-- Payment confirmation/refund confirmation is performed
-- only by trusted backend/service-role workflows.
-- =========================================================


-- =========================================================
-- 1. PAYMENT TRANSACTIONS
-- =========================================================

create table if not exists public.payment_transactions (

  id bigint
    generated by default as identity
    primary key,

  booking_id bigint not null
    references public.bookings(id)
    on delete restrict,

  traveler_id uuid not null
    references public.profiles(id)
    on delete restrict,

  payment_method text not null
    check (
      payment_method in (
        'pay_later',
        'cash',
        'bank_transfer',
        'online_card'
      )
    ),

  payment_processor text not null
    default 'manual',

  external_reference text,

  idempotency_key text not null unique,

  amount numeric(14,2) not null
    check (amount > 0),

  currency text not null,

  status text not null
    default 'pending'
    check (
      status in (
        'pending',
        'processing',
        'succeeded',
        'failed',
        'cancelled'
      )
    ),

  failure_reason text,

  metadata jsonb not null
    default '{}'::jsonb,

  succeeded_at timestamptz,

  created_at timestamptz not null
    default now(),

  updated_at timestamptz not null
    default now(),

  constraint payment_transaction_idempotency_not_blank
    check (
      length(trim(idempotency_key)) > 0
    ),

  constraint payment_transaction_currency_not_blank
    check (
      length(trim(currency)) > 0
    ),

  constraint payment_processor_not_blank
    check (
      length(trim(payment_processor)) > 0
    )
);


create index if not exists
payment_transactions_booking_idx
on public.payment_transactions(
  booking_id,
  created_at desc
);


create index if not exists
payment_transactions_traveler_idx
on public.payment_transactions(
  traveler_id,
  created_at desc
);


create index if not exists
payment_transactions_status_idx
on public.payment_transactions(
  status,
  created_at desc
);


create unique index if not exists
payment_transactions_external_reference_uidx
on public.payment_transactions(
  payment_processor,
  external_reference
)
where external_reference is not null;



-- =========================================================
-- 2. PAYMENT REFUNDS
-- =========================================================

create table if not exists public.payment_refunds (

  id bigint
    generated by default as identity
    primary key,

  payment_transaction_id bigint not null
    references public.payment_transactions(id)
    on delete restrict,

  booking_id bigint not null
    references public.bookings(id)
    on delete restrict,

  cancellation_id bigint
    references public.booking_cancellations(id)
    on delete set null,

  amount numeric(14,2) not null
    check (amount > 0),

  currency text not null,

  status text not null
    default 'pending'
    check (
      status in (
        'pending',
        'processing',
        'succeeded',
        'failed',
        'cancelled'
      )
    ),

  payment_processor text not null
    default 'manual',

  external_reference text,

  idempotency_key text not null unique,

  reason text,

  metadata jsonb not null
    default '{}'::jsonb,

  processed_at timestamptz,

  created_at timestamptz not null
    default now(),

  updated_at timestamptz not null
    default now(),

  constraint payment_refund_idempotency_not_blank
    check (
      length(trim(idempotency_key)) > 0
    )
);


create index if not exists
payment_refunds_transaction_idx
on public.payment_refunds(
  payment_transaction_id,
  created_at desc
);


create index if not exists
payment_refunds_booking_idx
on public.payment_refunds(
  booking_id,
  created_at desc
);


create index if not exists
payment_refunds_cancellation_idx
on public.payment_refunds(
  cancellation_id
)
where cancellation_id is not null;


create unique index if not exists
payment_refunds_external_reference_uidx
on public.payment_refunds(
  payment_processor,
  external_reference
)
where external_reference is not null;



-- =========================================================
-- 3. UPDATED_AT TRIGGERS
-- =========================================================

drop trigger if exists
set_payment_transactions_updated_at
on public.payment_transactions;

create trigger
set_payment_transactions_updated_at
before update
on public.payment_transactions
for each row
execute function public.set_updated_at();


drop trigger if exists
set_payment_refunds_updated_at
on public.payment_refunds;

create trigger
set_payment_refunds_updated_at
before update
on public.payment_refunds
for each row
execute function public.set_updated_at();



-- =========================================================
-- 4. RLS
-- =========================================================

alter table public.payment_transactions
enable row level security;

alter table public.payment_refunds
enable row level security;



-- Traveler sees only own payments.
-- Admin sees all.

drop policy if exists
"Traveler or admin views payments"
on public.payment_transactions;

create policy
"Traveler or admin views payments"
on public.payment_transactions
for select
to authenticated
using (
  traveler_id = auth.uid()
  or public.is_admin_user()
);



drop policy if exists
"Traveler or admin views refunds"
on public.payment_refunds;

create policy
"Traveler or admin views refunds"
on public.payment_refunds
for select
to authenticated
using (

  public.is_admin_user()

  or exists (
    select 1
    from public.payment_transactions pt
    where pt.id =
      payment_refunds.payment_transaction_id
      and pt.traveler_id = auth.uid()
  )
);



-- =========================================================
-- 5. BOOKING PAYMENT STATUS RECONCILIATION
--
-- Existing booking statuses supported:
--
-- unpaid
-- pending
-- paid
-- partially_refunded
-- refunded
-- failed
-- =========================================================

create or replace function
public.reconcile_booking_payment_status(
  p_booking_id bigint
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare

  v_total numeric := 0;

  v_successful_payments numeric := 0;
  v_successful_refunds numeric := 0;

  v_has_pending boolean := false;
  v_has_failed boolean := false;

  v_new_status text;

begin

  select coalesce(b.total_amount, 0)
  into v_total
  from public.bookings b
  where b.id = p_booking_id
  for update;


  if not found then
    raise exception 'Booking does not exist';
  end if;



  select
    coalesce(
      sum(pt.amount)
        filter (
          where pt.status = 'succeeded'
        ),
      0
    ),

    coalesce(
      bool_or(
        pt.status in (
          'pending',
          'processing'
        )
      ),
      false
    ),

    coalesce(
      bool_or(
        pt.status = 'failed'
      ),
      false
    )

  into
    v_successful_payments,
    v_has_pending,
    v_has_failed

  from public.payment_transactions pt

  where pt.booking_id = p_booking_id;



  select
    coalesce(
      sum(pr.amount)
        filter (
          where pr.status = 'succeeded'
        ),
      0
    ),

    (
      v_has_pending
      or
      coalesce(
        bool_or(
          pr.status in (
            'pending',
            'processing'
          )
        ),
        false
      )
    )

  into
    v_successful_refunds,
    v_has_pending

  from public.payment_refunds pr

  where pr.booking_id = p_booking_id;



  if v_successful_payments > 0
     and v_successful_refunds >=
         v_successful_payments then

    v_new_status := 'refunded';


  elsif v_successful_refunds > 0 then

    v_new_status := 'partially_refunded';


  elsif v_total > 0
     and v_successful_payments >=
         v_total then

    v_new_status := 'paid';


  elsif v_has_pending
     or v_successful_payments > 0 then

    -- Existing booking schema does not contain
    -- "partially_paid", therefore partial payment is
    -- represented as pending.
    v_new_status := 'pending';


  elsif v_has_failed then

    v_new_status := 'failed';


  else

    v_new_status := 'unpaid';

  end if;



  update public.bookings
  set payment_status = v_new_status
  where id = p_booking_id
    and payment_status is distinct from v_new_status;


  return v_new_status;

end;
$$;



-- =========================================================
-- 6. AUTOMATIC PAYMENT STATUS SYNC TRIGGER
-- =========================================================

create or replace function
public.sync_booking_payment_status()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin

  perform public.reconcile_booking_payment_status(
    coalesce(
      new.booking_id,
      old.booking_id
    )
  );

  return coalesce(new, old);

end;
$$;


drop trigger if exists
sync_booking_payment_from_transaction
on public.payment_transactions;

create trigger
sync_booking_payment_from_transaction
after insert
or update of status
on public.payment_transactions
for each row
execute function
public.sync_booking_payment_status();


drop trigger if exists
sync_booking_payment_from_refund
on public.payment_refunds;

create trigger
sync_booking_payment_from_refund
after insert
or update of status
on public.payment_refunds
for each row
execute function
public.sync_booking_payment_status();



-- =========================================================
-- 7. CREATE PAYMENT TRANSACTION
--
-- BACKEND / SERVICE ROLE ONLY.
--
-- Browser cannot directly call this.
-- =========================================================

create or replace function
public.create_payment_transaction(
  p_booking_id bigint,
  p_payment_method text,
  p_amount numeric,
  p_currency text,
  p_idempotency_key text,
  p_payment_processor text default 'manual',
  p_external_reference text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns public.payment_transactions
language plpgsql
security definer
set search_path = ''
as $$
declare

  v_booking public.bookings%rowtype;

  v_existing public.payment_transactions%rowtype;
  v_result public.payment_transactions%rowtype;

begin

  if p_payment_method not in (
    'pay_later',
    'cash',
    'bank_transfer',
    'online_card'
  ) then

    raise exception 'Invalid payment method';

  end if;


  if p_amount is null
     or p_amount <= 0 then

    raise exception
      'Payment amount must be greater than zero';

  end if;


  if nullif(
    trim(p_idempotency_key),
    ''
  ) is null then

    raise exception
      'Idempotency key is required';

  end if;



  select *
  into v_booking
  from public.bookings
  where id = p_booking_id
  for update;


  if not found then
    raise exception 'Booking does not exist';
  end if;


  if v_booking.status in (
    'cancelled',
    'failed',
    'expired'
  ) then

    raise exception
      'Payment cannot be created for this booking';

  end if;


  if upper(trim(p_currency))
     <> upper(trim(v_booking.currency)) then

    raise exception
      'Payment currency does not match booking currency';

  end if;


  if p_amount > v_booking.total_amount then

    raise exception
      'Payment amount exceeds booking total';

  end if;



  -- -------------------------------------------------------
  -- Idempotency
  -- -------------------------------------------------------

  select *
  into v_existing
  from public.payment_transactions
  where idempotency_key =
        trim(p_idempotency_key);


  if found then

    if v_existing.booking_id <> p_booking_id
       or v_existing.payment_method <>
          p_payment_method
       or v_existing.amount <> p_amount
       or upper(v_existing.currency) <>
          upper(trim(p_currency)) then

      raise exception
        'Idempotency key was already used for a different payment';

    end if;

    return v_existing;

  end if;



  insert into public.payment_transactions (
    booking_id,
    traveler_id,

    payment_method,
    payment_processor,

    external_reference,
    idempotency_key,

    amount,
    currency,

    status,
    metadata
  )
  values (
    v_booking.id,
    v_booking.traveler_id,

    p_payment_method,
    coalesce(
      nullif(
        trim(p_payment_processor),
        ''
      ),
      'manual'
    ),

    nullif(
      trim(p_external_reference),
      ''
    ),

    trim(p_idempotency_key),

    p_amount,
    upper(trim(p_currency)),

    'pending',

    coalesce(
      p_metadata,
      '{}'::jsonb
    )
  )
  returning *
  into v_result;


  return v_result;

end;
$$;



-- =========================================================
-- 8. UPDATE PAYMENT RESULT
--
-- Backend/gateway verified result only.
-- =========================================================

create or replace function
public.update_payment_transaction_status(
  p_transaction_id bigint,
  p_status text,
  p_external_reference text default null,
  p_failure_reason text default null,
  p_metadata jsonb default null
)
returns public.payment_transactions
language plpgsql
security definer
set search_path = ''
as $$
declare

  v_payment public.payment_transactions%rowtype;

  v_booking public.bookings%rowtype;

  v_other_successful_amount numeric := 0;

  v_result public.payment_transactions%rowtype;

begin

  if p_status not in (
    'pending',
    'processing',
    'succeeded',
    'failed',
    'cancelled'
  ) then

    raise exception
      'Invalid payment status';

  end if;



  select *
  into v_payment
  from public.payment_transactions
  where id = p_transaction_id
  for update;


  if not found then
    raise exception
      'Payment transaction does not exist';
  end if;



  -- Final statuses cannot be changed later.
  if v_payment.status in (
    'succeeded',
    'cancelled'
  )
  and v_payment.status <> p_status then

    raise exception
      'Finalized payment transaction cannot change status';

  end if;


  if v_payment.status = p_status then
    return v_payment;
  end if;



  select *
  into v_booking
  from public.bookings
  where id = v_payment.booking_id
  for update;



  if p_status = 'succeeded' then

    select coalesce(
      sum(pt.amount),
      0
    )
    into v_other_successful_amount

    from public.payment_transactions pt

    where pt.booking_id =
          v_payment.booking_id

      and pt.status = 'succeeded'

      and pt.id <>
          v_payment.id;


    if
      v_other_successful_amount
      + v_payment.amount
      > v_booking.total_amount
    then

      raise exception
        'Successful payments would exceed booking total';

    end if;

  end if;



  update public.payment_transactions
  set

    status = p_status,

    external_reference =
      coalesce(
        nullif(
          trim(p_external_reference),
          ''
        ),
        external_reference
      ),

    failure_reason =
      case
        when p_status = 'failed'
        then nullif(
          trim(p_failure_reason),
          ''
        )
        else null
      end,

    metadata =
      case
        when p_metadata is null
        then metadata
        else metadata || p_metadata
      end,

    succeeded_at =
      case
        when p_status = 'succeeded'
        then coalesce(
          succeeded_at,
          now()
        )
        else succeeded_at
      end

  where id = p_transaction_id

  returning *
  into v_result;


  return v_result;

end;
$$;



-- =========================================================
-- 9. CREATE REFUND
--
-- Refund begins as pending.
-- Backend/gateway later confirms success.
-- =========================================================

create or replace function
public.create_payment_refund(
  p_payment_transaction_id bigint,
  p_amount numeric,
  p_idempotency_key text,
  p_reason text default null,
  p_cancellation_id bigint default null,
  p_payment_processor text default null,
  p_external_reference text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns public.payment_refunds
language plpgsql
security definer
set search_path = ''
as $$
declare

  v_payment public.payment_transactions%rowtype;

  v_cancellation
    public.booking_cancellations%rowtype;

  v_existing public.payment_refunds%rowtype;

  v_reserved_refunds numeric := 0;
  v_cancellation_reserved numeric := 0;

  v_result public.payment_refunds%rowtype;

begin

  if p_amount is null
     or p_amount <= 0 then

    raise exception
      'Refund amount must be greater than zero';

  end if;


  if nullif(
    trim(p_idempotency_key),
    ''
  ) is null then

    raise exception
      'Refund idempotency key is required';

  end if;



  select *
  into v_payment
  from public.payment_transactions
  where id = p_payment_transaction_id
  for update;


  if not found then
    raise exception
      'Payment transaction does not exist';
  end if;


  if v_payment.status <> 'succeeded' then

    raise exception
      'Only a successful payment can be refunded';

  end if;



  -- -------------------------------------------------------
  -- Idempotency
  -- -------------------------------------------------------

  select *
  into v_existing
  from public.payment_refunds
  where idempotency_key =
        trim(p_idempotency_key);


  if found then

    if
      v_existing.payment_transaction_id
        <> p_payment_transaction_id

      or v_existing.amount <> p_amount
    then

      raise exception
        'Idempotency key was already used for a different refund';

    end if;

    return v_existing;

  end if;



  -- -------------------------------------------------------
  -- Prevent over-refunding same payment
  --
  -- pending + processing are included so two concurrent
  -- refunds cannot reserve the same money.
  -- -------------------------------------------------------

  select coalesce(
    sum(pr.amount),
    0
  )
  into v_reserved_refunds

  from public.payment_refunds pr

  where pr.payment_transaction_id =
        v_payment.id

    and pr.status in (
      'pending',
      'processing',
      'succeeded'
    );


  if v_reserved_refunds
     + p_amount
     > v_payment.amount then

    raise exception
      'Refund amount exceeds refundable payment balance';

  end if;



  -- -------------------------------------------------------
  -- Optional cancellation connection
  -- -------------------------------------------------------

  if p_cancellation_id is not null then

    select *
    into v_cancellation
    from public.booking_cancellations
    where id = p_cancellation_id
    for update;


    if not found then
      raise exception
        'Cancellation request does not exist';
    end if;


    if v_cancellation.booking_id
       <> v_payment.booking_id then

      raise exception
        'Cancellation does not belong to this booking';

    end if;


    if v_cancellation.status not in (
      'approved',
      'processed'
    ) then

      raise exception
        'Cancellation must be approved before refund';

    end if;


    if coalesce(
      v_cancellation.refund_amount,
      0
    ) <= 0 then

      raise exception
        'Cancellation has no approved refund amount';

    end if;



    select coalesce(
      sum(pr.amount),
      0
    )
    into v_cancellation_reserved

    from public.payment_refunds pr

    where pr.cancellation_id =
          p_cancellation_id

      and pr.status in (
        'pending',
        'processing',
        'succeeded'
      );


    if
      v_cancellation_reserved
      + p_amount
      > v_cancellation.refund_amount
    then

      raise exception
        'Refund exceeds approved cancellation refund amount';

    end if;

  end if;



  insert into public.payment_refunds (
    payment_transaction_id,
    booking_id,
    cancellation_id,

    amount,
    currency,

    status,
    payment_processor,

    external_reference,
    idempotency_key,

    reason,
    metadata
  )
  values (
    v_payment.id,
    v_payment.booking_id,
    p_cancellation_id,

    p_amount,
    v_payment.currency,

    'pending',

    coalesce(
      nullif(
        trim(p_payment_processor),
        ''
      ),
      v_payment.payment_processor
    ),

    nullif(
      trim(p_external_reference),
      ''
    ),

    trim(p_idempotency_key),

    nullif(
      trim(p_reason),
      ''
    ),

    coalesce(
      p_metadata,
      '{}'::jsonb
    )
  )
  returning *
  into v_result;


  return v_result;

end;
$$;



-- =========================================================
-- 10. UPDATE REFUND RESULT
-- =========================================================

create or replace function
public.update_payment_refund_status(
  p_refund_id bigint,
  p_status text,
  p_external_reference text default null,
  p_metadata jsonb default null
)
returns public.payment_refunds
language plpgsql
security definer
set search_path = ''
as $$
declare

  v_refund public.payment_refunds%rowtype;

  v_payment public.payment_transactions%rowtype;

  v_other_successful_refunds numeric := 0;

  v_result public.payment_refunds%rowtype;

begin

  if p_status not in (
    'pending',
    'processing',
    'succeeded',
    'failed',
    'cancelled'
  ) then

    raise exception
      'Invalid refund status';

  end if;



  select *
  into v_refund
  from public.payment_refunds
  where id = p_refund_id
  for update;


  if not found then
    raise exception 'Refund does not exist';
  end if;



  if v_refund.status in (
    'succeeded',
    'cancelled'
  )
  and v_refund.status <> p_status then

    raise exception
      'Finalized refund cannot change status';

  end if;


  if v_refund.status = p_status then
    return v_refund;
  end if;



  select *
  into v_payment
  from public.payment_transactions
  where id =
        v_refund.payment_transaction_id
  for update;



  if p_status = 'succeeded' then

    select coalesce(
      sum(pr.amount),
      0
    )
    into v_other_successful_refunds

    from public.payment_refunds pr

    where pr.payment_transaction_id =
          v_payment.id

      and pr.status = 'succeeded'

      and pr.id <> v_refund.id;


    if
      v_other_successful_refunds
      + v_refund.amount
      > v_payment.amount
    then

      raise exception
        'Successful refunds would exceed payment amount';

    end if;

  end if;



  update public.payment_refunds
  set

    status = p_status,

    external_reference =
      coalesce(
        nullif(
          trim(p_external_reference),
          ''
        ),
        external_reference
      ),

    metadata =
      case
        when p_metadata is null
        then metadata
        else metadata || p_metadata
      end,

    processed_at =
      case
        when p_status = 'succeeded'
        then coalesce(
          processed_at,
          now()
        )
        else processed_at
      end

  where id = p_refund_id

  returning *
  into v_result;


  return v_result;

end;
$$;



-- =========================================================
-- 11. CLIENT PRIVILEGES
--
-- Travelers may READ own payment history.
-- They may NOT insert/update/delete transaction records.
-- =========================================================

revoke all
on table public.payment_transactions
from anon, authenticated;

revoke all
on table public.payment_refunds
from anon, authenticated;


grant select
on table public.payment_transactions
to authenticated;

grant select
on table public.payment_refunds
to authenticated;



-- =========================================================
-- 12. INTERNAL FUNCTIONS
-- =========================================================

revoke all
on function
public.reconcile_booking_payment_status(bigint)
from public, anon, authenticated;


revoke all
on function
public.sync_booking_payment_status()
from public, anon, authenticated;



-- =========================================================
-- 13. TRUSTED BACKEND FUNCTIONS
--
-- IMPORTANT:
-- Do NOT grant these to authenticated browser clients.
-- =========================================================

revoke all
on function public.create_payment_transaction(
  bigint,
  text,
  numeric,
  text,
  text,
  text,
  text,
  jsonb
)
from public, anon, authenticated;


revoke all
on function public.update_payment_transaction_status(
  bigint,
  text,
  text,
  text,
  jsonb
)
from public, anon, authenticated;


revoke all
on function public.create_payment_refund(
  bigint,
  numeric,
  text,
  text,
  bigint,
  text,
  text,
  jsonb
)
from public, anon, authenticated;


revoke all
on function public.update_payment_refund_status(
  bigint,
  text,
  text,
  jsonb
)
from public, anon, authenticated;



grant execute
on function public.create_payment_transaction(
  bigint,
  text,
  numeric,
  text,
  text,
  text,
  text,
  jsonb
)
to service_role;


grant execute
on function public.update_payment_transaction_status(
  bigint,
  text,
  text,
  text,
  jsonb
)
to service_role;


grant execute
on function public.create_payment_refund(
  bigint,
  numeric,
  text,
  text,
  bigint,
  text,
  text,
  jsonb
)
to service_role;


grant execute
on function public.update_payment_refund_status(
  bigint,
  text,
  text,
  jsonb
)
to service_role;
