-- =========================================================
-- TripMate
-- Migration 036: Secure Transport Live Tracking
-- =========================================================


-- =========================================================
-- 1. LOCATION HISTORY
-- =========================================================

create table if not exists public.transport_location_updates (

  id bigint
    generated by default as identity
    primary key,

  transport_request_id bigint not null
    references public.transport_requests(id)
    on delete cascade,

  driver_id uuid not null
    references public.profiles(id)
    on delete restrict,

  vehicle_id bigint not null
    references public.vehicles(id)
    on delete restrict,

  latitude numeric(9,6) not null
    check (
      latitude >= -90
      and latitude <= 90
    ),

  longitude numeric(9,6) not null
    check (
      longitude >= -180
      and longitude <= 180
    ),

  accuracy_meters numeric(10,2)
    check (
      accuracy_meters is null
      or (
        accuracy_meters >= 0
        and accuracy_meters <= 10000
      )
    ),

  speed_kmh numeric(8,2)
    check (
      speed_kmh is null
      or (
        speed_kmh >= 0
        and speed_kmh <= 300
      )
    ),

  heading_degrees numeric(6,2)
    check (
      heading_degrees is null
      or (
        heading_degrees >= 0
        and heading_degrees < 360
      )
    ),

  recorded_at timestamptz not null
    default now(),

  created_at timestamptz not null
    default now()
);


create index if not exists
transport_location_request_time_idx
on public.transport_location_updates(
  transport_request_id,
  recorded_at desc,
  id desc
);


create index if not exists
transport_location_driver_time_idx
on public.transport_location_updates(
  driver_id,
  recorded_at desc
);



-- =========================================================
-- 2. RLS
-- =========================================================

alter table public.transport_location_updates
enable row level security;


drop policy if exists
"Trip parties view transport tracking"
on public.transport_location_updates;


create policy
"Trip parties view transport tracking"
on public.transport_location_updates
for select
to authenticated
using (

  public.is_admin_user()

  or driver_id = auth.uid()

  or exists (

    select 1

    from public.transport_requests tr

    where tr.id =
      transport_location_updates.transport_request_id

      and tr.traveler_id = auth.uid()

  )
);



-- =========================================================
-- 3. SECURE LOCATION SUBMISSION
--
-- Only the driver in the SELECTED + ACCEPTED bid can submit.
--
-- driver_id and vehicle_id are derived from driver_bids.
-- Client cannot spoof them.
-- =========================================================

create or replace function public.submit_transport_location(
  p_transport_request_id bigint,
  p_latitude numeric,
  p_longitude numeric,
  p_accuracy_meters numeric default null,
  p_speed_kmh numeric default null,
  p_heading_degrees numeric default null,
  p_recorded_at timestamptz default now()
)
returns public.transport_location_updates
language plpgsql
security definer
set search_path = ''
as $$
declare

  v_request public.transport_requests%rowtype;
  v_bid public.driver_bids%rowtype;

  v_result
    public.transport_location_updates%rowtype;

begin

  -- -------------------------------------------------------
  -- Authentication
  -- -------------------------------------------------------

  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;



  -- -------------------------------------------------------
  -- Coordinate validation
  -- -------------------------------------------------------

  if p_latitude is null
     or p_latitude < -90
     or p_latitude > 90 then

    raise exception 'Invalid latitude';

  end if;


  if p_longitude is null
     or p_longitude < -180
     or p_longitude > 180 then

    raise exception 'Invalid longitude';

  end if;


  if p_accuracy_meters is not null
     and (
       p_accuracy_meters < 0
       or p_accuracy_meters > 10000
     ) then

    raise exception 'Invalid GPS accuracy';

  end if;


  if p_speed_kmh is not null
     and (
       p_speed_kmh < 0
       or p_speed_kmh > 300
     ) then

    raise exception 'Invalid vehicle speed';

  end if;


  if p_heading_degrees is not null
     and (
       p_heading_degrees < 0
       or p_heading_degrees >= 360
     ) then

    raise exception 'Invalid heading';

  end if;



  -- -------------------------------------------------------
  -- Timestamp protection
  -- -------------------------------------------------------

  if p_recorded_at >
       now() + interval '5 minutes' then

    raise exception
      'Location timestamp cannot be in the future';

  end if;


  if p_recorded_at <
       now() - interval '24 hours' then

    raise exception
      'Location update is too old';

  end if;



  -- -------------------------------------------------------
  -- Lock transport request
  -- -------------------------------------------------------

  select *
  into v_request

  from public.transport_requests

  where id = p_transport_request_id

  for update;


  if not found then
    raise exception
      'Transport request does not exist';
  end if;



  -- -------------------------------------------------------
  -- Tracking is only valid after driver selection.
  -- -------------------------------------------------------

  if v_request.status <> 'driver_selected' then

    raise exception
      'Transport request is not active for tracking';

  end if;


  if v_request.selected_bid_id is null then

    raise exception
      'Transport request has no selected driver';

  end if;



  -- -------------------------------------------------------
  -- Privacy:
  -- Do not allow live driver tracking outside trip dates.
  -- -------------------------------------------------------

  if current_date < v_request.trip_start_date
     or current_date > v_request.trip_end_date then

    raise exception
      'Transport tracking is available only during the trip';

  end if;



  -- -------------------------------------------------------
  -- Load authoritative selected bid
  -- -------------------------------------------------------

  select *
  into v_bid

  from public.driver_bids

  where id = v_request.selected_bid_id
    and transport_request_id = v_request.id

  for share;


  if not found then

    raise exception
      'Selected transport bid does not exist';

  end if;


  if v_bid.status <> 'accepted' then

    raise exception
      'Selected transport bid is not accepted';

  end if;



  -- -------------------------------------------------------
  -- Only the selected driver can send GPS data.
  -- -------------------------------------------------------

  if v_bid.driver_id <> auth.uid() then

    raise exception
      'Only the selected driver can submit location updates';

  end if;



  -- -------------------------------------------------------
  -- Vehicle must still belong to selected driver.
  -- -------------------------------------------------------

  if not exists (

    select 1

    from public.vehicles v

    where v.id = v_bid.vehicle_id
      and v.driver_id = v_bid.driver_id

  ) then

    raise exception
      'Selected vehicle does not belong to this driver';

  end if;



  -- =======================================================
  -- INSERT AUTHORITATIVE LOCATION
  -- =======================================================

  insert into public.transport_location_updates (

    transport_request_id,

    driver_id,
    vehicle_id,

    latitude,
    longitude,

    accuracy_meters,
    speed_kmh,
    heading_degrees,

    recorded_at
  )

  values (

    v_request.id,

    v_bid.driver_id,
    v_bid.vehicle_id,

    p_latitude,
    p_longitude,

    p_accuracy_meters,
    p_speed_kmh,
    p_heading_degrees,

    p_recorded_at
  )

  returning *
  into v_result;


  return v_result;

end;
$$;



-- =========================================================
-- 4. CURRENT / LATEST LOCATION VIEW
--
-- One latest location per transport request.
--
-- security_invoker means underlying RLS still applies.
-- =========================================================

create or replace view public.current_transport_locations
with (security_invoker = true)
as

select distinct on (
  tlu.transport_request_id
)

  tlu.transport_request_id,

  tlu.driver_id,
  tlu.vehicle_id,

  tlu.latitude,
  tlu.longitude,

  tlu.accuracy_meters,
  tlu.speed_kmh,
  tlu.heading_degrees,

  tlu.recorded_at

from public.transport_location_updates tlu

order by
  tlu.transport_request_id,
  tlu.recorded_at desc,
  tlu.id desc;



-- =========================================================
-- 5. API PRIVILEGES
--
-- No browser direct INSERT / UPDATE / DELETE.
-- =========================================================

revoke all
on table public.transport_location_updates
from anon, authenticated;


grant select
on table public.transport_location_updates
to authenticated;


revoke all
on public.current_transport_locations
from anon, authenticated;


grant select
on public.current_transport_locations
to authenticated;



-- =========================================================
-- 6. RPC ACCESS
-- =========================================================

revoke all
on function public.submit_transport_location(
  bigint,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  timestamptz
)
from public, anon;


grant execute
on function public.submit_transport_location(
  bigint,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  timestamptz
)
to authenticated;
